// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: stakeholder/stakeholder.proto

package stakeholder

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Stakeholder_CreateUser_FullMethodName            = "/stakeholder.Stakeholder/CreateUser"
	Stakeholder_GetByID_FullMethodName               = "/stakeholder.Stakeholder/GetByID"
	Stakeholder_GetByUsername_FullMethodName         = "/stakeholder.Stakeholder/GetByUsername"
	Stakeholder_UpdateUser_FullMethodName            = "/stakeholder.Stakeholder/UpdateUser"
	Stakeholder_GetAll_FullMethodName                = "/stakeholder.Stakeholder/GetAll"
	Stakeholder_BlockUser_FullMethodName             = "/stakeholder.Stakeholder/BlockUser"
	Stakeholder_SetCurrentPosition_FullMethodName    = "/stakeholder.Stakeholder/SetCurrentPosition"
	Stakeholder_GetCurrentPosition_FullMethodName    = "/stakeholder.Stakeholder/GetCurrentPosition"
	Stakeholder_DeleteCurrentPosition_FullMethodName = "/stakeholder.Stakeholder/DeleteCurrentPosition"
)

// StakeholderClient is the client API for Stakeholder service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StakeholderClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	GetByID(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
	GetByUsername(ctx context.Context, in *GetUserByUsername, opts ...grpc.CallOption) (*GetUserResponse, error)
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error)
	GetAll(ctx context.Context, in *GetAllRequest, opts ...grpc.CallOption) (*GetAllResponse, error)
	BlockUser(ctx context.Context, in *BlockUserRequest, opts ...grpc.CallOption) (*BlockUserResponse, error)
	SetCurrentPosition(ctx context.Context, in *SetPositionRequest, opts ...grpc.CallOption) (*PositionResponse, error)
	GetCurrentPosition(ctx context.Context, in *GetPositionRequest, opts ...grpc.CallOption) (*PositionResponse, error)
	DeleteCurrentPosition(ctx context.Context, in *DeletePositionRequest, opts ...grpc.CallOption) (*DeletePositionResponse, error)
}

type stakeholderClient struct {
	cc grpc.ClientConnInterface
}

func NewStakeholderClient(cc grpc.ClientConnInterface) StakeholderClient {
	return &stakeholderClient{cc}
}

func (c *stakeholderClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, Stakeholder_CreateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stakeholderClient) GetByID(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, Stakeholder_GetByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stakeholderClient) GetByUsername(ctx context.Context, in *GetUserByUsername, opts ...grpc.CallOption) (*GetUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, Stakeholder_GetByUsername_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stakeholderClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateUserResponse)
	err := c.cc.Invoke(ctx, Stakeholder_UpdateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stakeholderClient) GetAll(ctx context.Context, in *GetAllRequest, opts ...grpc.CallOption) (*GetAllResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllResponse)
	err := c.cc.Invoke(ctx, Stakeholder_GetAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stakeholderClient) BlockUser(ctx context.Context, in *BlockUserRequest, opts ...grpc.CallOption) (*BlockUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BlockUserResponse)
	err := c.cc.Invoke(ctx, Stakeholder_BlockUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stakeholderClient) SetCurrentPosition(ctx context.Context, in *SetPositionRequest, opts ...grpc.CallOption) (*PositionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PositionResponse)
	err := c.cc.Invoke(ctx, Stakeholder_SetCurrentPosition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stakeholderClient) GetCurrentPosition(ctx context.Context, in *GetPositionRequest, opts ...grpc.CallOption) (*PositionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PositionResponse)
	err := c.cc.Invoke(ctx, Stakeholder_GetCurrentPosition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stakeholderClient) DeleteCurrentPosition(ctx context.Context, in *DeletePositionRequest, opts ...grpc.CallOption) (*DeletePositionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletePositionResponse)
	err := c.cc.Invoke(ctx, Stakeholder_DeleteCurrentPosition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StakeholderServer is the server API for Stakeholder service.
// All implementations must embed UnimplementedStakeholderServer
// for forward compatibility.
type StakeholderServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	GetByID(context.Context, *GetUserRequest) (*GetUserResponse, error)
	GetByUsername(context.Context, *GetUserByUsername) (*GetUserResponse, error)
	UpdateUser(context.Context, *UpdateUserRequest) (*UpdateUserResponse, error)
	GetAll(context.Context, *GetAllRequest) (*GetAllResponse, error)
	BlockUser(context.Context, *BlockUserRequest) (*BlockUserResponse, error)
	SetCurrentPosition(context.Context, *SetPositionRequest) (*PositionResponse, error)
	GetCurrentPosition(context.Context, *GetPositionRequest) (*PositionResponse, error)
	DeleteCurrentPosition(context.Context, *DeletePositionRequest) (*DeletePositionResponse, error)
	mustEmbedUnimplementedStakeholderServer()
}

// UnimplementedStakeholderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStakeholderServer struct{}

func (UnimplementedStakeholderServer) CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedStakeholderServer) GetByID(context.Context, *GetUserRequest) (*GetUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByID not implemented")
}
func (UnimplementedStakeholderServer) GetByUsername(context.Context, *GetUserByUsername) (*GetUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByUsername not implemented")
}
func (UnimplementedStakeholderServer) UpdateUser(context.Context, *UpdateUserRequest) (*UpdateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUser not implemented")
}
func (UnimplementedStakeholderServer) GetAll(context.Context, *GetAllRequest) (*GetAllResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}
func (UnimplementedStakeholderServer) BlockUser(context.Context, *BlockUserRequest) (*BlockUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BlockUser not implemented")
}
func (UnimplementedStakeholderServer) SetCurrentPosition(context.Context, *SetPositionRequest) (*PositionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetCurrentPosition not implemented")
}
func (UnimplementedStakeholderServer) GetCurrentPosition(context.Context, *GetPositionRequest) (*PositionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCurrentPosition not implemented")
}
func (UnimplementedStakeholderServer) DeleteCurrentPosition(context.Context, *DeletePositionRequest) (*DeletePositionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCurrentPosition not implemented")
}
func (UnimplementedStakeholderServer) mustEmbedUnimplementedStakeholderServer() {}
func (UnimplementedStakeholderServer) testEmbeddedByValue()                     {}

// UnsafeStakeholderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StakeholderServer will
// result in compilation errors.
type UnsafeStakeholderServer interface {
	mustEmbedUnimplementedStakeholderServer()
}

func RegisterStakeholderServer(s grpc.ServiceRegistrar, srv StakeholderServer) {
	// If the following call pancis, it indicates UnimplementedStakeholderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Stakeholder_ServiceDesc, srv)
}

func _Stakeholder_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StakeholderServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Stakeholder_CreateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StakeholderServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stakeholder_GetByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StakeholderServer).GetByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Stakeholder_GetByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StakeholderServer).GetByID(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stakeholder_GetByUsername_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserByUsername)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StakeholderServer).GetByUsername(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Stakeholder_GetByUsername_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StakeholderServer).GetByUsername(ctx, req.(*GetUserByUsername))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stakeholder_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StakeholderServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Stakeholder_UpdateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StakeholderServer).UpdateUser(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stakeholder_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StakeholderServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Stakeholder_GetAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StakeholderServer).GetAll(ctx, req.(*GetAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stakeholder_BlockUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlockUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StakeholderServer).BlockUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Stakeholder_BlockUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StakeholderServer).BlockUser(ctx, req.(*BlockUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stakeholder_SetCurrentPosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPositionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StakeholderServer).SetCurrentPosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Stakeholder_SetCurrentPosition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StakeholderServer).SetCurrentPosition(ctx, req.(*SetPositionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stakeholder_GetCurrentPosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPositionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StakeholderServer).GetCurrentPosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Stakeholder_GetCurrentPosition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StakeholderServer).GetCurrentPosition(ctx, req.(*GetPositionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stakeholder_DeleteCurrentPosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePositionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StakeholderServer).DeleteCurrentPosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Stakeholder_DeleteCurrentPosition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StakeholderServer).DeleteCurrentPosition(ctx, req.(*DeletePositionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Stakeholder_ServiceDesc is the grpc.ServiceDesc for Stakeholder service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Stakeholder_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stakeholder.Stakeholder",
	HandlerType: (*StakeholderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _Stakeholder_CreateUser_Handler,
		},
		{
			MethodName: "GetByID",
			Handler:    _Stakeholder_GetByID_Handler,
		},
		{
			MethodName: "GetByUsername",
			Handler:    _Stakeholder_GetByUsername_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _Stakeholder_UpdateUser_Handler,
		},
		{
			MethodName: "GetAll",
			Handler:    _Stakeholder_GetAll_Handler,
		},
		{
			MethodName: "BlockUser",
			Handler:    _Stakeholder_BlockUser_Handler,
		},
		{
			MethodName: "SetCurrentPosition",
			Handler:    _Stakeholder_SetCurrentPosition_Handler,
		},
		{
			MethodName: "GetCurrentPosition",
			Handler:    _Stakeholder_GetCurrentPosition_Handler,
		},
		{
			MethodName: "DeleteCurrentPosition",
			Handler:    _Stakeholder_DeleteCurrentPosition_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stakeholder/stakeholder.proto",
}
