// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: stakeholder/stakeholder.proto

package stakeholder

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	Blocked       bool                   `protobuf:"varint,5,opt,name=blocked,proto3" json:"blocked,omitempty"`
	FirstName     string                 `protobuf:"bytes,6,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,7,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	ProfileImage  string                 `protobuf:"bytes,8,opt,name=profile_image,json=profileImage,proto3" json:"profile_image,omitempty"`
	Bio           string                 `protobuf:"bytes,9,opt,name=bio,proto3" json:"bio,omitempty"`
	Motto         string                 `protobuf:"bytes,10,opt,name=motto,proto3" json:"motto,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_stakeholder_stakeholder_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_stakeholder_stakeholder_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_stakeholder_stakeholder_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *User) GetBlocked() bool {
	if x != nil {
		return x.Blocked
	}
	return false
}

func (x *User) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *User) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *User) GetProfileImage() string {
	if x != nil {
		return x.ProfileImage
	}
	return ""
}

func (x *User) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *User) GetMotto() string {
	if x != nil {
		return x.Motto
	}
	return ""
}

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_stakeholder_stakeholder_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stakeholder_stakeholder_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_stakeholder_stakeholder_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateUserRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type CreateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_stakeholder_stakeholder_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stakeholder_stakeholder_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_stakeholder_stakeholder_proto_rawDescGZIP(), []int{2}
}

func (x *CreateUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type GetUserByUsername struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByUsername) Reset() {
	*x = GetUserByUsername{}
	mi := &file_stakeholder_stakeholder_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByUsername) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByUsername) ProtoMessage() {}

func (x *GetUserByUsername) ProtoReflect() protoreflect.Message {
	mi := &file_stakeholder_stakeholder_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByUsername.ProtoReflect.Descriptor instead.
func (*GetUserByUsername) Descriptor() ([]byte, []int) {
	return file_stakeholder_stakeholder_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserByUsername) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_stakeholder_stakeholder_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stakeholder_stakeholder_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_stakeholder_stakeholder_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_stakeholder_stakeholder_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stakeholder_stakeholder_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_stakeholder_stakeholder_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	ProfileImage  string                 `protobuf:"bytes,4,opt,name=profile_image,json=profileImage,proto3" json:"profile_image,omitempty"`
	Bio           string                 `protobuf:"bytes,5,opt,name=bio,proto3" json:"bio,omitempty"`
	Motto         string                 `protobuf:"bytes,6,opt,name=motto,proto3" json:"motto,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_stakeholder_stakeholder_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stakeholder_stakeholder_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_stakeholder_stakeholder_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateUserRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UpdateUserRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *UpdateUserRequest) GetProfileImage() string {
	if x != nil {
		return x.ProfileImage
	}
	return ""
}

func (x *UpdateUserRequest) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *UpdateUserRequest) GetMotto() string {
	if x != nil {
		return x.Motto
	}
	return ""
}

type UpdateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserResponse) Reset() {
	*x = UpdateUserResponse{}
	mi := &file_stakeholder_stakeholder_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserResponse) ProtoMessage() {}

func (x *UpdateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stakeholder_stakeholder_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return file_stakeholder_stakeholder_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type BlockUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Block         bool                   `protobuf:"varint,2,opt,name=block,proto3" json:"block,omitempty"` // true = block, false = unblock
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockUserRequest) Reset() {
	*x = BlockUserRequest{}
	mi := &file_stakeholder_stakeholder_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockUserRequest) ProtoMessage() {}

func (x *BlockUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stakeholder_stakeholder_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockUserRequest.ProtoReflect.Descriptor instead.
func (*BlockUserRequest) Descriptor() ([]byte, []int) {
	return file_stakeholder_stakeholder_proto_rawDescGZIP(), []int{8}
}

func (x *BlockUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BlockUserRequest) GetBlock() bool {
	if x != nil {
		return x.Block
	}
	return false
}

type BlockUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockUserResponse) Reset() {
	*x = BlockUserResponse{}
	mi := &file_stakeholder_stakeholder_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockUserResponse) ProtoMessage() {}

func (x *BlockUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stakeholder_stakeholder_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockUserResponse.ProtoReflect.Descriptor instead.
func (*BlockUserResponse) Descriptor() ([]byte, []int) {
	return file_stakeholder_stakeholder_proto_rawDescGZIP(), []int{9}
}

func (x *BlockUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type GetAllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllRequest) Reset() {
	*x = GetAllRequest{}
	mi := &file_stakeholder_stakeholder_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRequest) ProtoMessage() {}

func (x *GetAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stakeholder_stakeholder_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllRequest.ProtoReflect.Descriptor instead.
func (*GetAllRequest) Descriptor() ([]byte, []int) {
	return file_stakeholder_stakeholder_proto_rawDescGZIP(), []int{10}
}

type GetAllResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllResponse) Reset() {
	*x = GetAllResponse{}
	mi := &file_stakeholder_stakeholder_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllResponse) ProtoMessage() {}

func (x *GetAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stakeholder_stakeholder_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllResponse.ProtoReflect.Descriptor instead.
func (*GetAllResponse) Descriptor() ([]byte, []int) {
	return file_stakeholder_stakeholder_proto_rawDescGZIP(), []int{11}
}

func (x *GetAllResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

var File_stakeholder_stakeholder_proto protoreflect.FileDescriptor

const file_stakeholder_stakeholder_proto_rawDesc = "" +
	"\n" +
	"\x1dstakeholder/stakeholder.proto\x12\vstakeholder\x1a\x1cgoogle/api/annotations.proto\"\xff\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12\x18\n" +
	"\ablocked\x18\x05 \x01(\bR\ablocked\x12\x1d\n" +
	"\n" +
	"first_name\x18\x06 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\a \x01(\tR\blastName\x12#\n" +
	"\rprofile_image\x18\b \x01(\tR\fprofileImage\x12\x10\n" +
	"\x03bio\x18\t \x01(\tR\x03bio\x12\x14\n" +
	"\x05motto\x18\n" +
	" \x01(\tR\x05motto\"u\n" +
	"\x11CreateUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\";\n" +
	"\x12CreateUserResponse\x12%\n" +
	"\x04user\x18\x01 \x01(\v2\x11.stakeholder.UserR\x04user\"/\n" +
	"\x11GetUserByUsername\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\" \n" +
	"\x0eGetUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"8\n" +
	"\x0fGetUserResponse\x12%\n" +
	"\x04user\x18\x01 \x01(\v2\x11.stakeholder.UserR\x04user\"\xac\x01\n" +
	"\x11UpdateUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12#\n" +
	"\rprofile_image\x18\x04 \x01(\tR\fprofileImage\x12\x10\n" +
	"\x03bio\x18\x05 \x01(\tR\x03bio\x12\x14\n" +
	"\x05motto\x18\x06 \x01(\tR\x05motto\";\n" +
	"\x12UpdateUserResponse\x12%\n" +
	"\x04user\x18\x01 \x01(\v2\x11.stakeholder.UserR\x04user\"8\n" +
	"\x10BlockUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05block\x18\x02 \x01(\bR\x05block\":\n" +
	"\x11BlockUserResponse\x12%\n" +
	"\x04user\x18\x01 \x01(\v2\x11.stakeholder.UserR\x04user\"\x0f\n" +
	"\rGetAllRequest\"9\n" +
	"\x0eGetAllResponse\x12'\n" +
	"\x05users\x18\x01 \x03(\v2\x11.stakeholder.UserR\x05users2\xf9\x04\n" +
	"\vStakeholder\x12d\n" +
	"\n" +
	"CreateUser\x12\x1e.stakeholder.CreateUserRequest\x1a\x1f.stakeholder.CreateUserResponse\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/api/users\x12]\n" +
	"\aGetByID\x12\x1b.stakeholder.GetUserRequest\x1a\x1c.stakeholder.GetUserResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/api/users/{id}\x12u\n" +
	"\rGetByUsername\x12\x1e.stakeholder.GetUserByUsername\x1a\x1c.stakeholder.GetUserResponse\"&\x82\xd3\xe4\x93\x02 \x12\x1e/api/users/username/{username}\x12i\n" +
	"\n" +
	"UpdateUser\x12\x1e.stakeholder.UpdateUserRequest\x1a\x1f.stakeholder.UpdateUserResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\x1a\x0f/api/users/{id}\x12U\n" +
	"\x06GetAll\x12\x1a.stakeholder.GetAllRequest\x1a\x1b.stakeholder.GetAllResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/api/users\x12l\n" +
	"\tBlockUser\x12\x1d.stakeholder.BlockUserRequest\x1a\x1e.stakeholder.BlockUserResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*2\x15/api/users/{id}/blockB\x13Z\x11proto/stakeholderb\x06proto3"

var (
	file_stakeholder_stakeholder_proto_rawDescOnce sync.Once
	file_stakeholder_stakeholder_proto_rawDescData []byte
)

func file_stakeholder_stakeholder_proto_rawDescGZIP() []byte {
	file_stakeholder_stakeholder_proto_rawDescOnce.Do(func() {
		file_stakeholder_stakeholder_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stakeholder_stakeholder_proto_rawDesc), len(file_stakeholder_stakeholder_proto_rawDesc)))
	})
	return file_stakeholder_stakeholder_proto_rawDescData
}

var file_stakeholder_stakeholder_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_stakeholder_stakeholder_proto_goTypes = []any{
	(*User)(nil),               // 0: stakeholder.User
	(*CreateUserRequest)(nil),  // 1: stakeholder.CreateUserRequest
	(*CreateUserResponse)(nil), // 2: stakeholder.CreateUserResponse
	(*GetUserByUsername)(nil),  // 3: stakeholder.GetUserByUsername
	(*GetUserRequest)(nil),     // 4: stakeholder.GetUserRequest
	(*GetUserResponse)(nil),    // 5: stakeholder.GetUserResponse
	(*UpdateUserRequest)(nil),  // 6: stakeholder.UpdateUserRequest
	(*UpdateUserResponse)(nil), // 7: stakeholder.UpdateUserResponse
	(*BlockUserRequest)(nil),   // 8: stakeholder.BlockUserRequest
	(*BlockUserResponse)(nil),  // 9: stakeholder.BlockUserResponse
	(*GetAllRequest)(nil),      // 10: stakeholder.GetAllRequest
	(*GetAllResponse)(nil),     // 11: stakeholder.GetAllResponse
}
var file_stakeholder_stakeholder_proto_depIdxs = []int32{
	0,  // 0: stakeholder.CreateUserResponse.user:type_name -> stakeholder.User
	0,  // 1: stakeholder.GetUserResponse.user:type_name -> stakeholder.User
	0,  // 2: stakeholder.UpdateUserResponse.user:type_name -> stakeholder.User
	0,  // 3: stakeholder.BlockUserResponse.user:type_name -> stakeholder.User
	0,  // 4: stakeholder.GetAllResponse.users:type_name -> stakeholder.User
	1,  // 5: stakeholder.Stakeholder.CreateUser:input_type -> stakeholder.CreateUserRequest
	4,  // 6: stakeholder.Stakeholder.GetByID:input_type -> stakeholder.GetUserRequest
	3,  // 7: stakeholder.Stakeholder.GetByUsername:input_type -> stakeholder.GetUserByUsername
	6,  // 8: stakeholder.Stakeholder.UpdateUser:input_type -> stakeholder.UpdateUserRequest
	10, // 9: stakeholder.Stakeholder.GetAll:input_type -> stakeholder.GetAllRequest
	8,  // 10: stakeholder.Stakeholder.BlockUser:input_type -> stakeholder.BlockUserRequest
	2,  // 11: stakeholder.Stakeholder.CreateUser:output_type -> stakeholder.CreateUserResponse
	5,  // 12: stakeholder.Stakeholder.GetByID:output_type -> stakeholder.GetUserResponse
	5,  // 13: stakeholder.Stakeholder.GetByUsername:output_type -> stakeholder.GetUserResponse
	7,  // 14: stakeholder.Stakeholder.UpdateUser:output_type -> stakeholder.UpdateUserResponse
	11, // 15: stakeholder.Stakeholder.GetAll:output_type -> stakeholder.GetAllResponse
	9,  // 16: stakeholder.Stakeholder.BlockUser:output_type -> stakeholder.BlockUserResponse
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_stakeholder_stakeholder_proto_init() }
func file_stakeholder_stakeholder_proto_init() {
	if File_stakeholder_stakeholder_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stakeholder_stakeholder_proto_rawDesc), len(file_stakeholder_stakeholder_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stakeholder_stakeholder_proto_goTypes,
		DependencyIndexes: file_stakeholder_stakeholder_proto_depIdxs,
		MessageInfos:      file_stakeholder_stakeholder_proto_msgTypes,
	}.Build()
	File_stakeholder_stakeholder_proto = out.File
	file_stakeholder_stakeholder_proto_goTypes = nil
	file_stakeholder_stakeholder_proto_depIdxs = nil
}
