// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: tour/tour.proto

package tour

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Tour struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AuthorId      string                 `protobuf:"bytes,2,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Difficulty    string                 `protobuf:"bytes,5,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Tags          []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	Price         float64                `protobuf:"fixed64,7,opt,name=price,proto3" json:"price,omitempty"`
	LengthKm      float64                `protobuf:"fixed64,8,opt,name=length_km,json=lengthKm,proto3" json:"length_km,omitempty"`
	Status        string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	TravelTimes   map[string]int32       `protobuf:"bytes,10,rep,name=travel_times,json=travelTimes,proto3" json:"travel_times,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	DepartureDate *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=departure_date,json=departureDate,proto3" json:"departure_date,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	PublishedAt   string                 `protobuf:"bytes,14,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	ArchivedAt    string                 `protobuf:"bytes,15,opt,name=archived_at,json=archivedAt,proto3" json:"archived_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tour) Reset() {
	*x = Tour{}
	mi := &file_tour_tour_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tour) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tour) ProtoMessage() {}

func (x *Tour) ProtoReflect() protoreflect.Message {
	mi := &file_tour_tour_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tour.ProtoReflect.Descriptor instead.
func (*Tour) Descriptor() ([]byte, []int) {
	return file_tour_tour_proto_rawDescGZIP(), []int{0}
}

func (x *Tour) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Tour) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *Tour) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tour) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Tour) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *Tour) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Tour) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Tour) GetLengthKm() float64 {
	if x != nil {
		return x.LengthKm
	}
	return 0
}

func (x *Tour) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Tour) GetTravelTimes() map[string]int32 {
	if x != nil {
		return x.TravelTimes
	}
	return nil
}

func (x *Tour) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Tour) GetDepartureDate() *timestamppb.Timestamp {
	if x != nil {
		return x.DepartureDate
	}
	return nil
}

func (x *Tour) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Tour) GetPublishedAt() string {
	if x != nil {
		return x.PublishedAt
	}
	return ""
}

func (x *Tour) GetArchivedAt() string {
	if x != nil {
		return x.ArchivedAt
	}
	return ""
}

type Keypoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TourId        string                 `protobuf:"bytes,2,opt,name=tour_id,json=tourId,proto3" json:"tour_id,omitempty"`
	Order         int32                  `protobuf:"varint,3,opt,name=order,proto3" json:"order,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Lat           float64                `protobuf:"fixed64,6,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float64                `protobuf:"fixed64,7,opt,name=lon,proto3" json:"lon,omitempty"`
	ImagePath     string                 `protobuf:"bytes,8,opt,name=image_path,json=imagePath,proto3" json:"image_path,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Keypoint) Reset() {
	*x = Keypoint{}
	mi := &file_tour_tour_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Keypoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Keypoint) ProtoMessage() {}

func (x *Keypoint) ProtoReflect() protoreflect.Message {
	mi := &file_tour_tour_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Keypoint.ProtoReflect.Descriptor instead.
func (*Keypoint) Descriptor() ([]byte, []int) {
	return file_tour_tour_proto_rawDescGZIP(), []int{1}
}

func (x *Keypoint) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Keypoint) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

func (x *Keypoint) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *Keypoint) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Keypoint) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Keypoint) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Keypoint) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *Keypoint) GetImagePath() string {
	if x != nil {
		return x.ImagePath
	}
	return ""
}

func (x *Keypoint) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Keypoint) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type Review struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TourId        string                 `protobuf:"bytes,2,opt,name=tour_id,json=tourId,proto3" json:"tour_id,omitempty"`
	TouristId     string                 `protobuf:"bytes,3,opt,name=tourist_id,json=touristId,proto3" json:"tourist_id,omitempty"`
	Rating        int32                  `protobuf:"varint,4,opt,name=rating,proto3" json:"rating,omitempty"`
	Comment       string                 `protobuf:"bytes,5,opt,name=comment,proto3" json:"comment,omitempty"`
	VisitDate     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=visit_date,json=visitDate,proto3" json:"visit_date,omitempty"`
	ImageUrls     []string               `protobuf:"bytes,7,rep,name=image_urls,json=imageUrls,proto3" json:"image_urls,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Review) Reset() {
	*x = Review{}
	mi := &file_tour_tour_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Review) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Review) ProtoMessage() {}

func (x *Review) ProtoReflect() protoreflect.Message {
	mi := &file_tour_tour_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Review.ProtoReflect.Descriptor instead.
func (*Review) Descriptor() ([]byte, []int) {
	return file_tour_tour_proto_rawDescGZIP(), []int{2}
}

func (x *Review) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Review) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

func (x *Review) GetTouristId() string {
	if x != nil {
		return x.TouristId
	}
	return ""
}

func (x *Review) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Review) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *Review) GetVisitDate() *timestamppb.Timestamp {
	if x != nil {
		return x.VisitDate
	}
	return nil
}

func (x *Review) GetImageUrls() []string {
	if x != nil {
		return x.ImageUrls
	}
	return nil
}

func (x *Review) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type TourExecution struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TourId             string                 `protobuf:"bytes,2,opt,name=tour_id,json=tourId,proto3" json:"tour_id,omitempty"`
	TouristId          string                 `protobuf:"bytes,3,opt,name=tourist_id,json=touristId,proto3" json:"tourist_id,omitempty"`
	Status             string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	CompletedKeyPoints []*CompletedKeyPoint   `protobuf:"bytes,5,rep,name=completed_key_points,json=completedKeyPoints,proto3" json:"completed_key_points,omitempty"`
	StartTime          *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime            *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	LastActivity       *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=last_activity,json=lastActivity,proto3" json:"last_activity,omitempty"`
	Lat                float64                `protobuf:"fixed64,9,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng                float64                `protobuf:"fixed64,10,opt,name=lng,proto3" json:"lng,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TourExecution) Reset() {
	*x = TourExecution{}
	mi := &file_tour_tour_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TourExecution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TourExecution) ProtoMessage() {}

func (x *TourExecution) ProtoReflect() protoreflect.Message {
	mi := &file_tour_tour_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TourExecution.ProtoReflect.Descriptor instead.
func (*TourExecution) Descriptor() ([]byte, []int) {
	return file_tour_tour_proto_rawDescGZIP(), []int{3}
}

func (x *TourExecution) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TourExecution) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

func (x *TourExecution) GetTouristId() string {
	if x != nil {
		return x.TouristId
	}
	return ""
}

func (x *TourExecution) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TourExecution) GetCompletedKeyPoints() []*CompletedKeyPoint {
	if x != nil {
		return x.CompletedKeyPoints
	}
	return nil
}

func (x *TourExecution) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *TourExecution) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *TourExecution) GetLastActivity() *timestamppb.Timestamp {
	if x != nil {
		return x.LastActivity
	}
	return nil
}

func (x *TourExecution) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *TourExecution) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

type CompletedKeyPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyPointId    string                 `protobuf:"bytes,1,opt,name=key_point_id,json=keyPointId,proto3" json:"key_point_id,omitempty"`
	CompletedTime *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=completed_time,json=completedTime,proto3" json:"completed_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompletedKeyPoint) Reset() {
	*x = CompletedKeyPoint{}
	mi := &file_tour_tour_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompletedKeyPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletedKeyPoint) ProtoMessage() {}

func (x *CompletedKeyPoint) ProtoReflect() protoreflect.Message {
	mi := &file_tour_tour_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletedKeyPoint.ProtoReflect.Descriptor instead.
func (*CompletedKeyPoint) Descriptor() ([]byte, []int) {
	return file_tour_tour_proto_rawDescGZIP(), []int{4}
}

func (x *CompletedKeyPoint) GetKeyPointId() string {
	if x != nil {
		return x.KeyPointId
	}
	return ""
}

func (x *CompletedKeyPoint) GetCompletedTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedTime
	}
	return nil
}

type StartTourRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TourId        string                 `protobuf:"bytes,1,opt,name=tour_id,json=tourId,proto3" json:"tour_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartTourRequest) Reset() {
	*x = StartTourRequest{}
	mi := &file_tour_tour_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTourRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTourRequest) ProtoMessage() {}

func (x *StartTourRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tour_tour_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTourRequest.ProtoReflect.Descriptor instead.
func (*StartTourRequest) Descriptor() ([]byte, []int) {
	return file_tour_tour_proto_rawDescGZIP(), []int{5}
}

func (x *StartTourRequest) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

type StartTourResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Execution     *TourExecution         `protobuf:"bytes,1,opt,name=execution,proto3" json:"execution,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartTourResponse) Reset() {
	*x = StartTourResponse{}
	mi := &file_tour_tour_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTourResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTourResponse) ProtoMessage() {}

func (x *StartTourResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tour_tour_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTourResponse.ProtoReflect.Descriptor instead.
func (*StartTourResponse) Descriptor() ([]byte, []int) {
	return file_tour_tour_proto_rawDescGZIP(), []int{6}
}

func (x *StartTourResponse) GetExecution() *TourExecution {
	if x != nil {
		return x.Execution
	}
	return nil
}

type UpdateTourExecutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Lat           float64                `protobuf:"fixed64,3,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng           float64                `protobuf:"fixed64,4,opt,name=lng,proto3" json:"lng,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTourExecutionRequest) Reset() {
	*x = UpdateTourExecutionRequest{}
	mi := &file_tour_tour_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTourExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTourExecutionRequest) ProtoMessage() {}

func (x *UpdateTourExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tour_tour_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTourExecutionRequest.ProtoReflect.Descriptor instead.
func (*UpdateTourExecutionRequest) Descriptor() ([]byte, []int) {
	return file_tour_tour_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateTourExecutionRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *UpdateTourExecutionRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateTourExecutionRequest) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *UpdateTourExecutionRequest) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

type UpdateTourExecutionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Execution     *TourExecution         `protobuf:"bytes,1,opt,name=execution,proto3" json:"execution,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTourExecutionResponse) Reset() {
	*x = UpdateTourExecutionResponse{}
	mi := &file_tour_tour_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTourExecutionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTourExecutionResponse) ProtoMessage() {}

func (x *UpdateTourExecutionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tour_tour_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTourExecutionResponse.ProtoReflect.Descriptor instead.
func (*UpdateTourExecutionResponse) Descriptor() ([]byte, []int) {
	return file_tour_tour_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateTourExecutionResponse) GetExecution() *TourExecution {
	if x != nil {
		return x.Execution
	}
	return nil
}

type CheckKeypointProximityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckKeypointProximityRequest) Reset() {
	*x = CheckKeypointProximityRequest{}
	mi := &file_tour_tour_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckKeypointProximityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckKeypointProximityRequest) ProtoMessage() {}

func (x *CheckKeypointProximityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tour_tour_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckKeypointProximityRequest.ProtoReflect.Descriptor instead.
func (*CheckKeypointProximityRequest) Descriptor() ([]byte, []int) {
	return file_tour_tour_proto_rawDescGZIP(), []int{9}
}

func (x *CheckKeypointProximityRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

type CheckKeypointProximityResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IsNearKeypoint bool                   `protobuf:"varint,1,opt,name=is_near_keypoint,json=isNearKeypoint,proto3" json:"is_near_keypoint,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CheckKeypointProximityResponse) Reset() {
	*x = CheckKeypointProximityResponse{}
	mi := &file_tour_tour_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckKeypointProximityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckKeypointProximityResponse) ProtoMessage() {}

func (x *CheckKeypointProximityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tour_tour_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckKeypointProximityResponse.ProtoReflect.Descriptor instead.
func (*CheckKeypointProximityResponse) Descriptor() ([]byte, []int) {
	return file_tour_tour_proto_rawDescGZIP(), []int{10}
}

func (x *CheckKeypointProximityResponse) GetIsNearKeypoint() bool {
	if x != nil {
		return x.IsNearKeypoint
	}
	return false
}

type CreateTourRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Difficulty    string                 `protobuf:"bytes,3,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	TravelTimes   map[string]int32       `protobuf:"bytes,5,rep,name=travel_times,json=travelTimes,proto3" json:"travel_times,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Price         float64                `protobuf:"fixed64,6,opt,name=price,proto3" json:"price,omitempty"`
	DepartureDate *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=departure_date,json=departureDate,proto3" json:"departure_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTourRequest) Reset() {
	*x = CreateTourRequest{}
	mi := &file_tour_tour_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTourRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTourRequest) ProtoMessage() {}

func (x *CreateTourRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tour_tour_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTourRequest.ProtoReflect.Descriptor instead.
func (*CreateTourRequest) Descriptor() ([]byte, []int) {
	return file_tour_tour_proto_rawDescGZIP(), []int{11}
}

func (x *CreateTourRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTourRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateTourRequest) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *CreateTourRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CreateTourRequest) GetTravelTimes() map[string]int32 {
	if x != nil {
		return x.TravelTimes
	}
	return nil
}

func (x *CreateTourRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateTourRequest) GetDepartureDate() *timestamppb.Timestamp {
	if x != nil {
		return x.DepartureDate
	}
	return nil
}

type CreateTourResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tour          *Tour                  `protobuf:"bytes,1,opt,name=tour,proto3" json:"tour,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTourResponse) Reset() {
	*x = CreateTourResponse{}
	mi := &file_tour_tour_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTourResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTourResponse) ProtoMessage() {}

func (x *CreateTourResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tour_tour_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTourResponse.ProtoReflect.Descriptor instead.
func (*CreateTourResponse) Descriptor() ([]byte, []int) {
	return file_tour_tour_proto_rawDescGZIP(), []int{12}
}

func (x *CreateTourResponse) GetTour() *Tour {
	if x != nil {
		return x.Tour
	}
	return nil
}

type GetToursByAuthorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthorId      string                 `protobuf:"bytes,1,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetToursByAuthorRequest) Reset() {
	*x = GetToursByAuthorRequest{}
	mi := &file_tour_tour_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetToursByAuthorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetToursByAuthorRequest) ProtoMessage() {}

func (x *GetToursByAuthorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tour_tour_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetToursByAuthorRequest.ProtoReflect.Descriptor instead.
func (*GetToursByAuthorRequest) Descriptor() ([]byte, []int) {
	return file_tour_tour_proto_rawDescGZIP(), []int{13}
}

func (x *GetToursByAuthorRequest) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

type GetToursByAuthorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tours         []*Tour                `protobuf:"bytes,1,rep,name=tours,proto3" json:"tours,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetToursByAuthorResponse) Reset() {
	*x = GetToursByAuthorResponse{}
	mi := &file_tour_tour_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetToursByAuthorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetToursByAuthorResponse) ProtoMessage() {}

func (x *GetToursByAuthorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tour_tour_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetToursByAuthorResponse.ProtoReflect.Descriptor instead.
func (*GetToursByAuthorResponse) Descriptor() ([]byte, []int) {
	return file_tour_tour_proto_rawDescGZIP(), []int{14}
}

func (x *GetToursByAuthorResponse) GetTours() []*Tour {
	if x != nil {
		return x.Tours
	}
	return nil
}

type GetTourRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTourRequest) Reset() {
	*x = GetTourRequest{}
	mi := &file_tour_tour_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTourRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTourRequest) ProtoMessage() {}

func (x *GetTourRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tour_tour_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTourRequest.ProtoReflect.Descriptor instead.
func (*GetTourRequest) Descriptor() ([]byte, []int) {
	return file_tour_tour_proto_rawDescGZIP(), []int{15}
}

func (x *GetTourRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTourResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tour          *Tour                  `protobuf:"bytes,1,opt,name=tour,proto3" json:"tour,omitempty"`
	Keypoints     []*Keypoint            `protobuf:"bytes,2,rep,name=keypoints,proto3" json:"keypoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTourResponse) Reset() {
	*x = GetTourResponse{}
	mi := &file_tour_tour_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTourResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTourResponse) ProtoMessage() {}

func (x *GetTourResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tour_tour_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTourResponse.ProtoReflect.Descriptor instead.
func (*GetTourResponse) Descriptor() ([]byte, []int) {
	return file_tour_tour_proto_rawDescGZIP(), []int{16}
}

func (x *GetTourResponse) GetTour() *Tour {
	if x != nil {
		return x.Tour
	}
	return nil
}

func (x *GetTourResponse) GetKeypoints() []*Keypoint {
	if x != nil {
		return x.Keypoints
	}
	return nil
}

type GetAllToursRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllToursRequest) Reset() {
	*x = GetAllToursRequest{}
	mi := &file_tour_tour_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllToursRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllToursRequest) ProtoMessage() {}

func (x *GetAllToursRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tour_tour_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllToursRequest.ProtoReflect.Descriptor instead.
func (*GetAllToursRequest) Descriptor() ([]byte, []int) {
	return file_tour_tour_proto_rawDescGZIP(), []int{17}
}

type GetAllToursResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tours         []*Tour                `protobuf:"bytes,1,rep,name=tours,proto3" json:"tours,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllToursResponse) Reset() {
	*x = GetAllToursResponse{}
	mi := &file_tour_tour_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllToursResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllToursResponse) ProtoMessage() {}

func (x *GetAllToursResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tour_tour_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllToursResponse.ProtoReflect.Descriptor instead.
func (*GetAllToursResponse) Descriptor() ([]byte, []int) {
	return file_tour_tour_proto_rawDescGZIP(), []int{18}
}

func (x *GetAllToursResponse) GetTours() []*Tour {
	if x != nil {
		return x.Tours
	}
	return nil
}

type CreateReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TourId        string                 `protobuf:"bytes,1,opt,name=tour_id,json=tourId,proto3" json:"tour_id,omitempty"`
	Rating        int32                  `protobuf:"varint,2,opt,name=rating,proto3" json:"rating,omitempty"`
	Comment       string                 `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	VisitDate     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=visit_date,json=visitDate,proto3" json:"visit_date,omitempty"`
	Images        []*Image               `protobuf:"bytes,5,rep,name=images,proto3" json:"images,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReviewRequest) Reset() {
	*x = CreateReviewRequest{}
	mi := &file_tour_tour_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReviewRequest) ProtoMessage() {}

func (x *CreateReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tour_tour_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReviewRequest.ProtoReflect.Descriptor instead.
func (*CreateReviewRequest) Descriptor() ([]byte, []int) {
	return file_tour_tour_proto_rawDescGZIP(), []int{19}
}

func (x *CreateReviewRequest) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

func (x *CreateReviewRequest) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *CreateReviewRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *CreateReviewRequest) GetVisitDate() *timestamppb.Timestamp {
	if x != nil {
		return x.VisitDate
	}
	return nil
}

func (x *CreateReviewRequest) GetImages() []*Image {
	if x != nil {
		return x.Images
	}
	return nil
}

type Image struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Image) Reset() {
	*x = Image{}
	mi := &file_tour_tour_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image) ProtoMessage() {}

func (x *Image) ProtoReflect() protoreflect.Message {
	mi := &file_tour_tour_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Image.ProtoReflect.Descriptor instead.
func (*Image) Descriptor() ([]byte, []int) {
	return file_tour_tour_proto_rawDescGZIP(), []int{20}
}

func (x *Image) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Image) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *Image) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type CreateReviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Review        *Review                `protobuf:"bytes,1,opt,name=review,proto3" json:"review,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReviewResponse) Reset() {
	*x = CreateReviewResponse{}
	mi := &file_tour_tour_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReviewResponse) ProtoMessage() {}

func (x *CreateReviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tour_tour_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReviewResponse.ProtoReflect.Descriptor instead.
func (*CreateReviewResponse) Descriptor() ([]byte, []int) {
	return file_tour_tour_proto_rawDescGZIP(), []int{21}
}

func (x *CreateReviewResponse) GetReview() *Review {
	if x != nil {
		return x.Review
	}
	return nil
}

type GetReviewsByTourRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TourId        string                 `protobuf:"bytes,1,opt,name=tourId,proto3" json:"tourId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReviewsByTourRequest) Reset() {
	*x = GetReviewsByTourRequest{}
	mi := &file_tour_tour_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReviewsByTourRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReviewsByTourRequest) ProtoMessage() {}

func (x *GetReviewsByTourRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tour_tour_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReviewsByTourRequest.ProtoReflect.Descriptor instead.
func (*GetReviewsByTourRequest) Descriptor() ([]byte, []int) {
	return file_tour_tour_proto_rawDescGZIP(), []int{22}
}

func (x *GetReviewsByTourRequest) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

type GetReviewsByTourResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reviews       []*Review              `protobuf:"bytes,1,rep,name=reviews,proto3" json:"reviews,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReviewsByTourResponse) Reset() {
	*x = GetReviewsByTourResponse{}
	mi := &file_tour_tour_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReviewsByTourResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReviewsByTourResponse) ProtoMessage() {}

func (x *GetReviewsByTourResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tour_tour_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReviewsByTourResponse.ProtoReflect.Descriptor instead.
func (*GetReviewsByTourResponse) Descriptor() ([]byte, []int) {
	return file_tour_tour_proto_rawDescGZIP(), []int{23}
}

func (x *GetReviewsByTourResponse) GetReviews() []*Review {
	if x != nil {
		return x.Reviews
	}
	return nil
}

type UpdateTourRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Difficulty    string                 `protobuf:"bytes,4,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	TravelTimes   map[string]int32       `protobuf:"bytes,6,rep,name=travel_times,json=travelTimes,proto3" json:"travel_times,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	LengthKm      float64                `protobuf:"fixed64,7,opt,name=length_km,json=lengthKm,proto3" json:"length_km,omitempty"`
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	Price         float64                `protobuf:"fixed64,9,opt,name=price,proto3" json:"price,omitempty"`
	DepartureDate *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=departure_date,json=departureDate,proto3" json:"departure_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTourRequest) Reset() {
	*x = UpdateTourRequest{}
	mi := &file_tour_tour_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTourRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTourRequest) ProtoMessage() {}

func (x *UpdateTourRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tour_tour_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTourRequest.ProtoReflect.Descriptor instead.
func (*UpdateTourRequest) Descriptor() ([]byte, []int) {
	return file_tour_tour_proto_rawDescGZIP(), []int{24}
}

func (x *UpdateTourRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTourRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateTourRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateTourRequest) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *UpdateTourRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *UpdateTourRequest) GetTravelTimes() map[string]int32 {
	if x != nil {
		return x.TravelTimes
	}
	return nil
}

func (x *UpdateTourRequest) GetLengthKm() float64 {
	if x != nil {
		return x.LengthKm
	}
	return 0
}

func (x *UpdateTourRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateTourRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UpdateTourRequest) GetDepartureDate() *timestamppb.Timestamp {
	if x != nil {
		return x.DepartureDate
	}
	return nil
}

type UpdateTourResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tour          *Tour                  `protobuf:"bytes,1,opt,name=tour,proto3" json:"tour,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTourResponse) Reset() {
	*x = UpdateTourResponse{}
	mi := &file_tour_tour_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTourResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTourResponse) ProtoMessage() {}

func (x *UpdateTourResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tour_tour_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTourResponse.ProtoReflect.Descriptor instead.
func (*UpdateTourResponse) Descriptor() ([]byte, []int) {
	return file_tour_tour_proto_rawDescGZIP(), []int{25}
}

func (x *UpdateTourResponse) GetTour() *Tour {
	if x != nil {
		return x.Tour
	}
	return nil
}

type AddKeypointRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TourId           string                 `protobuf:"bytes,1,opt,name=tour_id,json=tourId,proto3" json:"tour_id,omitempty"`
	Order            int32                  `protobuf:"varint,2,opt,name=order,proto3" json:"order,omitempty"`
	Name             string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description      string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Lat              float64                `protobuf:"fixed64,5,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon              float64                `protobuf:"fixed64,6,opt,name=lon,proto3" json:"lon,omitempty"`
	Image            []byte                 `protobuf:"bytes,7,opt,name=image,proto3" json:"image,omitempty"`                                                 // optional raw bytes
	ImageFilename    string                 `protobuf:"bytes,8,opt,name=image_filename,json=imageFilename,proto3" json:"image_filename,omitempty"`            // optional
	ImageContentType string                 `protobuf:"bytes,9,opt,name=image_content_type,json=imageContentType,proto3" json:"image_content_type,omitempty"` // optional
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AddKeypointRequest) Reset() {
	*x = AddKeypointRequest{}
	mi := &file_tour_tour_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddKeypointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddKeypointRequest) ProtoMessage() {}

func (x *AddKeypointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tour_tour_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddKeypointRequest.ProtoReflect.Descriptor instead.
func (*AddKeypointRequest) Descriptor() ([]byte, []int) {
	return file_tour_tour_proto_rawDescGZIP(), []int{26}
}

func (x *AddKeypointRequest) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

func (x *AddKeypointRequest) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *AddKeypointRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddKeypointRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AddKeypointRequest) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *AddKeypointRequest) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *AddKeypointRequest) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *AddKeypointRequest) GetImageFilename() string {
	if x != nil {
		return x.ImageFilename
	}
	return ""
}

func (x *AddKeypointRequest) GetImageContentType() string {
	if x != nil {
		return x.ImageContentType
	}
	return ""
}

type AddKeypointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keypoint      *Keypoint              `protobuf:"bytes,1,opt,name=keypoint,proto3" json:"keypoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddKeypointResponse) Reset() {
	*x = AddKeypointResponse{}
	mi := &file_tour_tour_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddKeypointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddKeypointResponse) ProtoMessage() {}

func (x *AddKeypointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tour_tour_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddKeypointResponse.ProtoReflect.Descriptor instead.
func (*AddKeypointResponse) Descriptor() ([]byte, []int) {
	return file_tour_tour_proto_rawDescGZIP(), []int{27}
}

func (x *AddKeypointResponse) GetKeypoint() *Keypoint {
	if x != nil {
		return x.Keypoint
	}
	return nil
}

type GetKeypointImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeypointId    string                 `protobuf:"bytes,1,opt,name=keypoint_id,json=keypointId,proto3" json:"keypoint_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeypointImageRequest) Reset() {
	*x = GetKeypointImageRequest{}
	mi := &file_tour_tour_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeypointImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeypointImageRequest) ProtoMessage() {}

func (x *GetKeypointImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tour_tour_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeypointImageRequest.ProtoReflect.Descriptor instead.
func (*GetKeypointImageRequest) Descriptor() ([]byte, []int) {
	return file_tour_tour_proto_rawDescGZIP(), []int{28}
}

func (x *GetKeypointImageRequest) GetKeypointId() string {
	if x != nil {
		return x.KeypointId
	}
	return ""
}

type ImageChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageChunk) Reset() {
	*x = ImageChunk{}
	mi := &file_tour_tour_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageChunk) ProtoMessage() {}

func (x *ImageChunk) ProtoReflect() protoreflect.Message {
	mi := &file_tour_tour_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageChunk.ProtoReflect.Descriptor instead.
func (*ImageChunk) Descriptor() ([]byte, []int) {
	return file_tour_tour_proto_rawDescGZIP(), []int{29}
}

func (x *ImageChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ReorderKeypointsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TourId        string                 `protobuf:"bytes,1,opt,name=tour_id,json=tourId,proto3" json:"tour_id,omitempty"`
	OrderedIds    []string               `protobuf:"bytes,2,rep,name=ordered_ids,json=orderedIds,proto3" json:"ordered_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReorderKeypointsRequest) Reset() {
	*x = ReorderKeypointsRequest{}
	mi := &file_tour_tour_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReorderKeypointsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReorderKeypointsRequest) ProtoMessage() {}

func (x *ReorderKeypointsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tour_tour_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReorderKeypointsRequest.ProtoReflect.Descriptor instead.
func (*ReorderKeypointsRequest) Descriptor() ([]byte, []int) {
	return file_tour_tour_proto_rawDescGZIP(), []int{30}
}

func (x *ReorderKeypointsRequest) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

func (x *ReorderKeypointsRequest) GetOrderedIds() []string {
	if x != nil {
		return x.OrderedIds
	}
	return nil
}

type ReorderKeypointsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReorderKeypointsResponse) Reset() {
	*x = ReorderKeypointsResponse{}
	mi := &file_tour_tour_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReorderKeypointsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReorderKeypointsResponse) ProtoMessage() {}

func (x *ReorderKeypointsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tour_tour_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReorderKeypointsResponse.ProtoReflect.Descriptor instead.
func (*ReorderKeypointsResponse) Descriptor() ([]byte, []int) {
	return file_tour_tour_proto_rawDescGZIP(), []int{31}
}

func (x *ReorderKeypointsResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type UpdateKeypointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeypointId    string                 `protobuf:"bytes,1,opt,name=keypoint_id,json=keypointId,proto3" json:"keypoint_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Lat           float64                `protobuf:"fixed64,4,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float64                `protobuf:"fixed64,5,opt,name=lon,proto3" json:"lon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateKeypointRequest) Reset() {
	*x = UpdateKeypointRequest{}
	mi := &file_tour_tour_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateKeypointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateKeypointRequest) ProtoMessage() {}

func (x *UpdateKeypointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tour_tour_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateKeypointRequest.ProtoReflect.Descriptor instead.
func (*UpdateKeypointRequest) Descriptor() ([]byte, []int) {
	return file_tour_tour_proto_rawDescGZIP(), []int{32}
}

func (x *UpdateKeypointRequest) GetKeypointId() string {
	if x != nil {
		return x.KeypointId
	}
	return ""
}

func (x *UpdateKeypointRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateKeypointRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateKeypointRequest) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *UpdateKeypointRequest) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

type UpdateKeypointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keypoint      *Keypoint              `protobuf:"bytes,1,opt,name=keypoint,proto3" json:"keypoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateKeypointResponse) Reset() {
	*x = UpdateKeypointResponse{}
	mi := &file_tour_tour_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateKeypointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateKeypointResponse) ProtoMessage() {}

func (x *UpdateKeypointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tour_tour_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateKeypointResponse.ProtoReflect.Descriptor instead.
func (*UpdateKeypointResponse) Descriptor() ([]byte, []int) {
	return file_tour_tour_proto_rawDescGZIP(), []int{33}
}

func (x *UpdateKeypointResponse) GetKeypoint() *Keypoint {
	if x != nil {
		return x.Keypoint
	}
	return nil
}

type DeleteKeypointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeypointId    string                 `protobuf:"bytes,1,opt,name=keypoint_id,json=keypointId,proto3" json:"keypoint_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKeypointRequest) Reset() {
	*x = DeleteKeypointRequest{}
	mi := &file_tour_tour_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKeypointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKeypointRequest) ProtoMessage() {}

func (x *DeleteKeypointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tour_tour_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKeypointRequest.ProtoReflect.Descriptor instead.
func (*DeleteKeypointRequest) Descriptor() ([]byte, []int) {
	return file_tour_tour_proto_rawDescGZIP(), []int{34}
}

func (x *DeleteKeypointRequest) GetKeypointId() string {
	if x != nil {
		return x.KeypointId
	}
	return ""
}

type DeleteKeypointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKeypointResponse) Reset() {
	*x = DeleteKeypointResponse{}
	mi := &file_tour_tour_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKeypointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKeypointResponse) ProtoMessage() {}

func (x *DeleteKeypointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tour_tour_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKeypointResponse.ProtoReflect.Descriptor instead.
func (*DeleteKeypointResponse) Descriptor() ([]byte, []int) {
	return file_tour_tour_proto_rawDescGZIP(), []int{35}
}

func (x *DeleteKeypointResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type GetCompletionStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompletionStatusRequest) Reset() {
	*x = GetCompletionStatusRequest{}
	mi := &file_tour_tour_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompletionStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompletionStatusRequest) ProtoMessage() {}

func (x *GetCompletionStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tour_tour_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompletionStatusRequest.ProtoReflect.Descriptor instead.
func (*GetCompletionStatusRequest) Descriptor() ([]byte, []int) {
	return file_tour_tour_proto_rawDescGZIP(), []int{36}
}

func (x *GetCompletionStatusRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

type GetCompletionStatusResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CompletedKeypoints int32                  `protobuf:"varint,1,opt,name=completed_keypoints,json=completedKeypoints,proto3" json:"completed_keypoints,omitempty"`
	TotalKeypoints     int32                  `protobuf:"varint,2,opt,name=total_keypoints,json=totalKeypoints,proto3" json:"total_keypoints,omitempty"`
	AllCompleted       bool                   `protobuf:"varint,3,opt,name=all_completed,json=allCompleted,proto3" json:"all_completed,omitempty"`
	Progress           string                 `protobuf:"bytes,4,opt,name=progress,proto3" json:"progress,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetCompletionStatusResponse) Reset() {
	*x = GetCompletionStatusResponse{}
	mi := &file_tour_tour_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompletionStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompletionStatusResponse) ProtoMessage() {}

func (x *GetCompletionStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tour_tour_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompletionStatusResponse.ProtoReflect.Descriptor instead.
func (*GetCompletionStatusResponse) Descriptor() ([]byte, []int) {
	return file_tour_tour_proto_rawDescGZIP(), []int{37}
}

func (x *GetCompletionStatusResponse) GetCompletedKeypoints() int32 {
	if x != nil {
		return x.CompletedKeypoints
	}
	return 0
}

func (x *GetCompletionStatusResponse) GetTotalKeypoints() int32 {
	if x != nil {
		return x.TotalKeypoints
	}
	return 0
}

func (x *GetCompletionStatusResponse) GetAllCompleted() bool {
	if x != nil {
		return x.AllCompleted
	}
	return false
}

func (x *GetCompletionStatusResponse) GetProgress() string {
	if x != nil {
		return x.Progress
	}
	return ""
}

type GetTourExecutionByUserAndTourRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TouristId     string                 `protobuf:"bytes,1,opt,name=tourist_id,json=touristId,proto3" json:"tourist_id,omitempty"`
	TourId        string                 `protobuf:"bytes,2,opt,name=tour_id,json=tourId,proto3" json:"tour_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTourExecutionByUserAndTourRequest) Reset() {
	*x = GetTourExecutionByUserAndTourRequest{}
	mi := &file_tour_tour_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTourExecutionByUserAndTourRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTourExecutionByUserAndTourRequest) ProtoMessage() {}

func (x *GetTourExecutionByUserAndTourRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tour_tour_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTourExecutionByUserAndTourRequest.ProtoReflect.Descriptor instead.
func (*GetTourExecutionByUserAndTourRequest) Descriptor() ([]byte, []int) {
	return file_tour_tour_proto_rawDescGZIP(), []int{38}
}

func (x *GetTourExecutionByUserAndTourRequest) GetTouristId() string {
	if x != nil {
		return x.TouristId
	}
	return ""
}

func (x *GetTourExecutionByUserAndTourRequest) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

type GetTourExecutionByUserAndTourResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Execution     *TourExecution         `protobuf:"bytes,1,opt,name=execution,proto3" json:"execution,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTourExecutionByUserAndTourResponse) Reset() {
	*x = GetTourExecutionByUserAndTourResponse{}
	mi := &file_tour_tour_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTourExecutionByUserAndTourResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTourExecutionByUserAndTourResponse) ProtoMessage() {}

func (x *GetTourExecutionByUserAndTourResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tour_tour_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTourExecutionByUserAndTourResponse.ProtoReflect.Descriptor instead.
func (*GetTourExecutionByUserAndTourResponse) Descriptor() ([]byte, []int) {
	return file_tour_tour_proto_rawDescGZIP(), []int{39}
}

func (x *GetTourExecutionByUserAndTourResponse) GetExecution() *TourExecution {
	if x != nil {
		return x.Execution
	}
	return nil
}

type CheckReviewExistsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TourId        string                 `protobuf:"bytes,1,opt,name=tour_id,json=tourId,proto3" json:"tour_id,omitempty"`
	TouristId     string                 `protobuf:"bytes,2,opt,name=tourist_id,json=touristId,proto3" json:"tourist_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckReviewExistsRequest) Reset() {
	*x = CheckReviewExistsRequest{}
	mi := &file_tour_tour_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckReviewExistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckReviewExistsRequest) ProtoMessage() {}

func (x *CheckReviewExistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tour_tour_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckReviewExistsRequest.ProtoReflect.Descriptor instead.
func (*CheckReviewExistsRequest) Descriptor() ([]byte, []int) {
	return file_tour_tour_proto_rawDescGZIP(), []int{40}
}

func (x *CheckReviewExistsRequest) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

func (x *CheckReviewExistsRequest) GetTouristId() string {
	if x != nil {
		return x.TouristId
	}
	return ""
}

type CheckReviewExistsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	ReviewId      string                 `protobuf:"bytes,2,opt,name=review_id,json=reviewId,proto3" json:"review_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckReviewExistsResponse) Reset() {
	*x = CheckReviewExistsResponse{}
	mi := &file_tour_tour_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckReviewExistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckReviewExistsResponse) ProtoMessage() {}

func (x *CheckReviewExistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tour_tour_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckReviewExistsResponse.ProtoReflect.Descriptor instead.
func (*CheckReviewExistsResponse) Descriptor() ([]byte, []int) {
	return file_tour_tour_proto_rawDescGZIP(), []int{41}
}

func (x *CheckReviewExistsResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *CheckReviewExistsResponse) GetReviewId() string {
	if x != nil {
		return x.ReviewId
	}
	return ""
}

var File_tour_tour_proto protoreflect.FileDescriptor

const file_tour_tour_proto_rawDesc = "" +
	"\n" +
	"\x0ftour/tour.proto\x12\x04tour\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\"\xc9\x04\n" +
	"\x04Tour\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tauthor_id\x18\x02 \x01(\tR\bauthorId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x05 \x01(\tR\n" +
	"difficulty\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x12\x14\n" +
	"\x05price\x18\a \x01(\x01R\x05price\x12\x1b\n" +
	"\tlength_km\x18\b \x01(\x01R\blengthKm\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x12>\n" +
	"\ftravel_times\x18\n" +
	" \x03(\v2\x1b.tour.Tour.TravelTimesEntryR\vtravelTimes\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12A\n" +
	"\x0edeparture_date\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\rdepartureDate\x12\x1d\n" +
	"\n" +
	"updated_at\x18\r \x01(\tR\tupdatedAt\x12!\n" +
	"\fpublished_at\x18\x0e \x01(\tR\vpublishedAt\x12\x1f\n" +
	"\varchived_at\x18\x0f \x01(\tR\n" +
	"archivedAt\x1a>\n" +
	"\x10TravelTimesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\x80\x02\n" +
	"\bKeypoint\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\atour_id\x18\x02 \x01(\tR\x06tourId\x12\x14\n" +
	"\x05order\x18\x03 \x01(\x05R\x05order\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x10\n" +
	"\x03lat\x18\x06 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\a \x01(\x01R\x03lon\x12\x1d\n" +
	"\n" +
	"image_path\x18\b \x01(\tR\timagePath\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tR\tupdatedAt\"\x97\x02\n" +
	"\x06Review\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\atour_id\x18\x02 \x01(\tR\x06tourId\x12\x1d\n" +
	"\n" +
	"tourist_id\x18\x03 \x01(\tR\ttouristId\x12\x16\n" +
	"\x06rating\x18\x04 \x01(\x05R\x06rating\x12\x18\n" +
	"\acomment\x18\x05 \x01(\tR\acomment\x129\n" +
	"\n" +
	"visit_date\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tvisitDate\x12\x1d\n" +
	"\n" +
	"image_urls\x18\a \x03(\tR\timageUrls\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x91\x03\n" +
	"\rTourExecution\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\atour_id\x18\x02 \x01(\tR\x06tourId\x12\x1d\n" +
	"\n" +
	"tourist_id\x18\x03 \x01(\tR\ttouristId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12I\n" +
	"\x14completed_key_points\x18\x05 \x03(\v2\x17.tour.CompletedKeyPointR\x12completedKeyPoints\x129\n" +
	"\n" +
	"start_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12?\n" +
	"\rlast_activity\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\flastActivity\x12\x10\n" +
	"\x03lat\x18\t \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lng\x18\n" +
	" \x01(\x01R\x03lng\"x\n" +
	"\x11CompletedKeyPoint\x12 \n" +
	"\fkey_point_id\x18\x01 \x01(\tR\n" +
	"keyPointId\x12A\n" +
	"\x0ecompleted_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\rcompletedTime\"+\n" +
	"\x10StartTourRequest\x12\x17\n" +
	"\atour_id\x18\x01 \x01(\tR\x06tourId\"F\n" +
	"\x11StartTourResponse\x121\n" +
	"\texecution\x18\x01 \x01(\v2\x13.tour.TourExecutionR\texecution\"{\n" +
	"\x1aUpdateTourExecutionRequest\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x10\n" +
	"\x03lat\x18\x03 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lng\x18\x04 \x01(\x01R\x03lng\"P\n" +
	"\x1bUpdateTourExecutionResponse\x121\n" +
	"\texecution\x18\x01 \x01(\v2\x13.tour.TourExecutionR\texecution\"B\n" +
	"\x1dCheckKeypointProximityRequest\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\"J\n" +
	"\x1eCheckKeypointProximityResponse\x12(\n" +
	"\x10is_near_keypoint\x18\x01 \x01(\bR\x0eisNearKeypoint\"\xe3\x02\n" +
	"\x11CreateTourRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x03 \x01(\tR\n" +
	"difficulty\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x12K\n" +
	"\ftravel_times\x18\x05 \x03(\v2(.tour.CreateTourRequest.TravelTimesEntryR\vtravelTimes\x12\x14\n" +
	"\x05price\x18\x06 \x01(\x01R\x05price\x12A\n" +
	"\x0edeparture_date\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\rdepartureDate\x1a>\n" +
	"\x10TravelTimesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"4\n" +
	"\x12CreateTourResponse\x12\x1e\n" +
	"\x04tour\x18\x01 \x01(\v2\n" +
	".tour.TourR\x04tour\"6\n" +
	"\x17GetToursByAuthorRequest\x12\x1b\n" +
	"\tauthor_id\x18\x01 \x01(\tR\bauthorId\"<\n" +
	"\x18GetToursByAuthorResponse\x12 \n" +
	"\x05tours\x18\x01 \x03(\v2\n" +
	".tour.TourR\x05tours\" \n" +
	"\x0eGetTourRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"_\n" +
	"\x0fGetTourResponse\x12\x1e\n" +
	"\x04tour\x18\x01 \x01(\v2\n" +
	".tour.TourR\x04tour\x12,\n" +
	"\tkeypoints\x18\x02 \x03(\v2\x0e.tour.KeypointR\tkeypoints\"\x14\n" +
	"\x12GetAllToursRequest\"7\n" +
	"\x13GetAllToursResponse\x12 \n" +
	"\x05tours\x18\x01 \x03(\v2\n" +
	".tour.TourR\x05tours\"\xc0\x01\n" +
	"\x13CreateReviewRequest\x12\x17\n" +
	"\atour_id\x18\x01 \x01(\tR\x06tourId\x12\x16\n" +
	"\x06rating\x18\x02 \x01(\x05R\x06rating\x12\x18\n" +
	"\acomment\x18\x03 \x01(\tR\acomment\x129\n" +
	"\n" +
	"visit_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tvisitDate\x12#\n" +
	"\x06images\x18\x05 \x03(\v2\v.tour.ImageR\x06images\"Z\n" +
	"\x05Image\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\"<\n" +
	"\x14CreateReviewResponse\x12$\n" +
	"\x06review\x18\x01 \x01(\v2\f.tour.ReviewR\x06review\"1\n" +
	"\x17GetReviewsByTourRequest\x12\x16\n" +
	"\x06tourId\x18\x01 \x01(\tR\x06tourId\"B\n" +
	"\x18GetReviewsByTourResponse\x12&\n" +
	"\areviews\x18\x01 \x03(\v2\f.tour.ReviewR\areviews\"\xa8\x03\n" +
	"\x11UpdateTourRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x04 \x01(\tR\n" +
	"difficulty\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x12K\n" +
	"\ftravel_times\x18\x06 \x03(\v2(.tour.UpdateTourRequest.TravelTimesEntryR\vtravelTimes\x12\x1b\n" +
	"\tlength_km\x18\a \x01(\x01R\blengthKm\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12\x14\n" +
	"\x05price\x18\t \x01(\x01R\x05price\x12A\n" +
	"\x0edeparture_date\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\rdepartureDate\x1a>\n" +
	"\x10TravelTimesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"4\n" +
	"\x12UpdateTourResponse\x12\x1e\n" +
	"\x04tour\x18\x01 \x01(\v2\n" +
	".tour.TourR\x04tour\"\x88\x02\n" +
	"\x12AddKeypointRequest\x12\x17\n" +
	"\atour_id\x18\x01 \x01(\tR\x06tourId\x12\x14\n" +
	"\x05order\x18\x02 \x01(\x05R\x05order\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x10\n" +
	"\x03lat\x18\x05 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\x06 \x01(\x01R\x03lon\x12\x14\n" +
	"\x05image\x18\a \x01(\fR\x05image\x12%\n" +
	"\x0eimage_filename\x18\b \x01(\tR\rimageFilename\x12,\n" +
	"\x12image_content_type\x18\t \x01(\tR\x10imageContentType\"A\n" +
	"\x13AddKeypointResponse\x12*\n" +
	"\bkeypoint\x18\x01 \x01(\v2\x0e.tour.KeypointR\bkeypoint\":\n" +
	"\x17GetKeypointImageRequest\x12\x1f\n" +
	"\vkeypoint_id\x18\x01 \x01(\tR\n" +
	"keypointId\" \n" +
	"\n" +
	"ImageChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"S\n" +
	"\x17ReorderKeypointsRequest\x12\x17\n" +
	"\atour_id\x18\x01 \x01(\tR\x06tourId\x12\x1f\n" +
	"\vordered_ids\x18\x02 \x03(\tR\n" +
	"orderedIds\"*\n" +
	"\x18ReorderKeypointsResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\x92\x01\n" +
	"\x15UpdateKeypointRequest\x12\x1f\n" +
	"\vkeypoint_id\x18\x01 \x01(\tR\n" +
	"keypointId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x10\n" +
	"\x03lat\x18\x04 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\x05 \x01(\x01R\x03lon\"D\n" +
	"\x16UpdateKeypointResponse\x12*\n" +
	"\bkeypoint\x18\x01 \x01(\v2\x0e.tour.KeypointR\bkeypoint\"8\n" +
	"\x15DeleteKeypointRequest\x12\x1f\n" +
	"\vkeypoint_id\x18\x01 \x01(\tR\n" +
	"keypointId\"(\n" +
	"\x16DeleteKeypointResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"?\n" +
	"\x1aGetCompletionStatusRequest\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\"\xb8\x01\n" +
	"\x1bGetCompletionStatusResponse\x12/\n" +
	"\x13completed_keypoints\x18\x01 \x01(\x05R\x12completedKeypoints\x12'\n" +
	"\x0ftotal_keypoints\x18\x02 \x01(\x05R\x0etotalKeypoints\x12#\n" +
	"\rall_completed\x18\x03 \x01(\bR\fallCompleted\x12\x1a\n" +
	"\bprogress\x18\x04 \x01(\tR\bprogress\"^\n" +
	"$GetTourExecutionByUserAndTourRequest\x12\x1d\n" +
	"\n" +
	"tourist_id\x18\x01 \x01(\tR\ttouristId\x12\x17\n" +
	"\atour_id\x18\x02 \x01(\tR\x06tourId\"Z\n" +
	"%GetTourExecutionByUserAndTourResponse\x121\n" +
	"\texecution\x18\x01 \x01(\v2\x13.tour.TourExecutionR\texecution\"R\n" +
	"\x18CheckReviewExistsRequest\x12\x17\n" +
	"\atour_id\x18\x01 \x01(\tR\x06tourId\x12\x1d\n" +
	"\n" +
	"tourist_id\x18\x02 \x01(\tR\ttouristId\"P\n" +
	"\x19CheckReviewExistsResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\x12\x1b\n" +
	"\treview_id\x18\x02 \x01(\tR\breviewId2\xeb\x10\n" +
	"\vTourService\x12U\n" +
	"\n" +
	"CreateTour\x12\x17.tour.CreateTourRequest\x1a\x18.tour.CreateTourResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/api/tour\x12q\n" +
	"\x10GetToursByAuthor\x12\x1d.tour.GetToursByAuthorRequest\x1a\x1e.tour.GetToursByAuthorResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/api/tours/{author_id}\x12N\n" +
	"\aGetTour\x12\x14.tour.GetTourRequest\x1a\x15.tour.GetTourResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/api/tour/{id}\x12V\n" +
	"\vGetAllTours\x12\x18.tour.GetAllToursRequest\x1a\x19.tour.GetAllToursResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/api/tours\x12]\n" +
	"\fCreateReview\x12\x19.tour.CreateReviewRequest\x1a\x1a.tour.CreateReviewResponse\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/api/review\x12Z\n" +
	"\n" +
	"UpdateTour\x12\x17.tour.UpdateTourRequest\x1a\x18.tour.UpdateTourResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\x1a\x0e/api/tour/{id}\x12p\n" +
	"\x10GetReviewsByTour\x12\x1d.tour.GetReviewsByTourRequest\x1a\x1e.tour.GetReviewsByTourResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/api/reviews/{tourId}\x12l\n" +
	"\vAddKeypoint\x12\x18.tour.AddKeypointRequest\x1a\x19.tour.AddKeypointResponse\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/api/tour/{tour_id}/keypoints\x12q\n" +
	"\x10GetKeypointImage\x12\x1d.tour.GetKeypointImageRequest\x1a\x10.tour.ImageChunk\"*\x82\xd3\xe4\x93\x02$\x12\"/api/keypoints/{keypoint_id}/image0\x01\x12\x84\x01\n" +
	"\x10ReorderKeypoints\x12\x1d.tour.ReorderKeypointsRequest\x1a\x1e.tour.ReorderKeypointsResponse\"1\x82\xd3\xe4\x93\x02+:\x01*\"&/api/tours/{tour_id}/keypoints/reorder\x12t\n" +
	"\x0eUpdateKeypoint\x12\x1b.tour.UpdateKeypointRequest\x1a\x1c.tour.UpdateKeypointResponse\"'\x82\xd3\xe4\x93\x02!:\x01*\x1a\x1c/api/keypoints/{keypoint_id}\x12q\n" +
	"\x0eDeleteKeypoint\x12\x1b.tour.DeleteKeypointRequest\x1a\x1c.tour.DeleteKeypointResponse\"$\x82\xd3\xe4\x93\x02\x1e*\x1c/api/keypoints/{keypoint_id}\x12\\\n" +
	"\tStartTour\x12\x16.tour.StartTourRequest\x1a\x17.tour.StartTourResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/tour-execution\x12\x89\x01\n" +
	"\x13UpdateTourExecution\x12 .tour.UpdateTourExecutionRequest\x1a!.tour.UpdateTourExecutionResponse\"-\x82\xd3\xe4\x93\x02':\x01*\x1a\"/api/tour-execution/{execution_id}\x12\x9f\x01\n" +
	"\x16CheckKeypointProximity\x12#.tour.CheckKeypointProximityRequest\x1a$.tour.CheckKeypointProximityResponse\":\x82\xd3\xe4\x93\x024\x122/api/tour-execution/{execution_id}/check-proximity\x12\x98\x01\n" +
	"\x13GetCompletionStatus\x12 .tour.GetCompletionStatusRequest\x1a!.tour.GetCompletionStatusResponse\"<\x82\xd3\xe4\x93\x026\x124/api/tour-execution/{execution_id}/completion-status\x12\x88\x01\n" +
	"\x11CheckReviewExists\x12\x1e.tour.CheckReviewExistsRequest\x1a\x1f.tour.CheckReviewExistsResponse\"2\x82\xd3\xe4\x93\x02,\x12*/api/reviews/{tour_id}/{tourist_id}/exists\x12\xb9\x01\n" +
	"\x1dGetTourExecutionByUserAndTour\x12*.tour.GetTourExecutionByUserAndTourRequest\x1a+.tour.GetTourExecutionByUserAndTourResponse\"?\x82\xd3\xe4\x93\x029\x127/api/tour-execution/tourist/{tourist_id}/tour/{tour_id}B\fZ\n" +
	"proto/tourb\x06proto3"

var (
	file_tour_tour_proto_rawDescOnce sync.Once
	file_tour_tour_proto_rawDescData []byte
)

func file_tour_tour_proto_rawDescGZIP() []byte {
	file_tour_tour_proto_rawDescOnce.Do(func() {
		file_tour_tour_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tour_tour_proto_rawDesc), len(file_tour_tour_proto_rawDesc)))
	})
	return file_tour_tour_proto_rawDescData
}

var file_tour_tour_proto_msgTypes = make([]protoimpl.MessageInfo, 45)
var file_tour_tour_proto_goTypes = []any{
	(*Tour)(nil),                                  // 0: tour.Tour
	(*Keypoint)(nil),                              // 1: tour.Keypoint
	(*Review)(nil),                                // 2: tour.Review
	(*TourExecution)(nil),                         // 3: tour.TourExecution
	(*CompletedKeyPoint)(nil),                     // 4: tour.CompletedKeyPoint
	(*StartTourRequest)(nil),                      // 5: tour.StartTourRequest
	(*StartTourResponse)(nil),                     // 6: tour.StartTourResponse
	(*UpdateTourExecutionRequest)(nil),            // 7: tour.UpdateTourExecutionRequest
	(*UpdateTourExecutionResponse)(nil),           // 8: tour.UpdateTourExecutionResponse
	(*CheckKeypointProximityRequest)(nil),         // 9: tour.CheckKeypointProximityRequest
	(*CheckKeypointProximityResponse)(nil),        // 10: tour.CheckKeypointProximityResponse
	(*CreateTourRequest)(nil),                     // 11: tour.CreateTourRequest
	(*CreateTourResponse)(nil),                    // 12: tour.CreateTourResponse
	(*GetToursByAuthorRequest)(nil),               // 13: tour.GetToursByAuthorRequest
	(*GetToursByAuthorResponse)(nil),              // 14: tour.GetToursByAuthorResponse
	(*GetTourRequest)(nil),                        // 15: tour.GetTourRequest
	(*GetTourResponse)(nil),                       // 16: tour.GetTourResponse
	(*GetAllToursRequest)(nil),                    // 17: tour.GetAllToursRequest
	(*GetAllToursResponse)(nil),                   // 18: tour.GetAllToursResponse
	(*CreateReviewRequest)(nil),                   // 19: tour.CreateReviewRequest
	(*Image)(nil),                                 // 20: tour.Image
	(*CreateReviewResponse)(nil),                  // 21: tour.CreateReviewResponse
	(*GetReviewsByTourRequest)(nil),               // 22: tour.GetReviewsByTourRequest
	(*GetReviewsByTourResponse)(nil),              // 23: tour.GetReviewsByTourResponse
	(*UpdateTourRequest)(nil),                     // 24: tour.UpdateTourRequest
	(*UpdateTourResponse)(nil),                    // 25: tour.UpdateTourResponse
	(*AddKeypointRequest)(nil),                    // 26: tour.AddKeypointRequest
	(*AddKeypointResponse)(nil),                   // 27: tour.AddKeypointResponse
	(*GetKeypointImageRequest)(nil),               // 28: tour.GetKeypointImageRequest
	(*ImageChunk)(nil),                            // 29: tour.ImageChunk
	(*ReorderKeypointsRequest)(nil),               // 30: tour.ReorderKeypointsRequest
	(*ReorderKeypointsResponse)(nil),              // 31: tour.ReorderKeypointsResponse
	(*UpdateKeypointRequest)(nil),                 // 32: tour.UpdateKeypointRequest
	(*UpdateKeypointResponse)(nil),                // 33: tour.UpdateKeypointResponse
	(*DeleteKeypointRequest)(nil),                 // 34: tour.DeleteKeypointRequest
	(*DeleteKeypointResponse)(nil),                // 35: tour.DeleteKeypointResponse
	(*GetCompletionStatusRequest)(nil),            // 36: tour.GetCompletionStatusRequest
	(*GetCompletionStatusResponse)(nil),           // 37: tour.GetCompletionStatusResponse
	(*GetTourExecutionByUserAndTourRequest)(nil),  // 38: tour.GetTourExecutionByUserAndTourRequest
	(*GetTourExecutionByUserAndTourResponse)(nil), // 39: tour.GetTourExecutionByUserAndTourResponse
	(*CheckReviewExistsRequest)(nil),              // 40: tour.CheckReviewExistsRequest
	(*CheckReviewExistsResponse)(nil),             // 41: tour.CheckReviewExistsResponse
	nil,                                           // 42: tour.Tour.TravelTimesEntry
	nil,                                           // 43: tour.CreateTourRequest.TravelTimesEntry
	nil,                                           // 44: tour.UpdateTourRequest.TravelTimesEntry
	(*timestamppb.Timestamp)(nil),                 // 45: google.protobuf.Timestamp
}
var file_tour_tour_proto_depIdxs = []int32{
	38, // 0: tour.Tour.travel_times:type_name -> tour.Tour.TravelTimesEntry
	41, // 1: tour.Tour.created_at:type_name -> google.protobuf.Timestamp
	41, // 2: tour.Tour.departure_date:type_name -> google.protobuf.Timestamp
	41, // 3: tour.Review.visit_date:type_name -> google.protobuf.Timestamp
	41, // 4: tour.Review.created_at:type_name -> google.protobuf.Timestamp
	4,  // 5: tour.TourExecution.completed_key_points:type_name -> tour.CompletedKeyPoint
	41, // 6: tour.TourExecution.start_time:type_name -> google.protobuf.Timestamp
	41, // 7: tour.TourExecution.end_time:type_name -> google.protobuf.Timestamp
	41, // 8: tour.TourExecution.last_activity:type_name -> google.protobuf.Timestamp
	41, // 9: tour.CompletedKeyPoint.completed_time:type_name -> google.protobuf.Timestamp
	3,  // 10: tour.StartTourResponse.execution:type_name -> tour.TourExecution
	3,  // 11: tour.UpdateTourExecutionResponse.execution:type_name -> tour.TourExecution
	39, // 12: tour.CreateTourRequest.travel_times:type_name -> tour.CreateTourRequest.TravelTimesEntry
	41, // 13: tour.CreateTourRequest.departure_date:type_name -> google.protobuf.Timestamp
	0,  // 14: tour.CreateTourResponse.tour:type_name -> tour.Tour
	0,  // 15: tour.GetToursByAuthorResponse.tours:type_name -> tour.Tour
	0,  // 16: tour.GetTourResponse.tour:type_name -> tour.Tour
	1,  // 17: tour.GetTourResponse.keypoints:type_name -> tour.Keypoint
	0,  // 18: tour.GetAllToursResponse.tours:type_name -> tour.Tour
	41, // 19: tour.CreateReviewRequest.visit_date:type_name -> google.protobuf.Timestamp
	20, // 20: tour.CreateReviewRequest.images:type_name -> tour.Image
	2,  // 21: tour.CreateReviewResponse.review:type_name -> tour.Review
	2,  // 22: tour.GetReviewsByTourResponse.reviews:type_name -> tour.Review
	40, // 23: tour.UpdateTourRequest.travel_times:type_name -> tour.UpdateTourRequest.TravelTimesEntry
	41, // 24: tour.UpdateTourRequest.departure_date:type_name -> google.protobuf.Timestamp
	0,  // 25: tour.UpdateTourResponse.tour:type_name -> tour.Tour
	1,  // 26: tour.AddKeypointResponse.keypoint:type_name -> tour.Keypoint
	1,  // 27: tour.UpdateKeypointResponse.keypoint:type_name -> tour.Keypoint
	11, // 28: tour.TourService.CreateTour:input_type -> tour.CreateTourRequest
	13, // 29: tour.TourService.GetToursByAuthor:input_type -> tour.GetToursByAuthorRequest
	15, // 30: tour.TourService.GetTour:input_type -> tour.GetTourRequest
	17, // 31: tour.TourService.GetAllTours:input_type -> tour.GetAllToursRequest
	19, // 32: tour.TourService.CreateReview:input_type -> tour.CreateReviewRequest
	24, // 33: tour.TourService.UpdateTour:input_type -> tour.UpdateTourRequest
	22, // 34: tour.TourService.GetReviewsByTour:input_type -> tour.GetReviewsByTourRequest
	26, // 35: tour.TourService.AddKeypoint:input_type -> tour.AddKeypointRequest
	28, // 36: tour.TourService.GetKeypointImage:input_type -> tour.GetKeypointImageRequest
	30, // 37: tour.TourService.ReorderKeypoints:input_type -> tour.ReorderKeypointsRequest
	32, // 38: tour.TourService.UpdateKeypoint:input_type -> tour.UpdateKeypointRequest
	34, // 39: tour.TourService.DeleteKeypoint:input_type -> tour.DeleteKeypointRequest
	5,  // 40: tour.TourService.StartTour:input_type -> tour.StartTourRequest
	7,  // 41: tour.TourService.UpdateTourExecution:input_type -> tour.UpdateTourExecutionRequest
	9,  // 42: tour.TourService.CheckKeypointProximity:input_type -> tour.CheckKeypointProximityRequest
	36, // 43: tour.TourService.GetCompletionStatus:input_type -> tour.GetCompletionStatusRequest
	12, // 44: tour.TourService.CreateTour:output_type -> tour.CreateTourResponse
	14, // 45: tour.TourService.GetToursByAuthor:output_type -> tour.GetToursByAuthorResponse
	16, // 46: tour.TourService.GetTour:output_type -> tour.GetTourResponse
	18, // 47: tour.TourService.GetAllTours:output_type -> tour.GetAllToursResponse
	21, // 48: tour.TourService.CreateReview:output_type -> tour.CreateReviewResponse
	25, // 49: tour.TourService.UpdateTour:output_type -> tour.UpdateTourResponse
	23, // 50: tour.TourService.GetReviewsByTour:output_type -> tour.GetReviewsByTourResponse
	27, // 51: tour.TourService.AddKeypoint:output_type -> tour.AddKeypointResponse
	29, // 52: tour.TourService.GetKeypointImage:output_type -> tour.ImageChunk
	31, // 53: tour.TourService.ReorderKeypoints:output_type -> tour.ReorderKeypointsResponse
	33, // 54: tour.TourService.UpdateKeypoint:output_type -> tour.UpdateKeypointResponse
	35, // 55: tour.TourService.DeleteKeypoint:output_type -> tour.DeleteKeypointResponse
	6,  // 56: tour.TourService.StartTour:output_type -> tour.StartTourResponse
	8,  // 57: tour.TourService.UpdateTourExecution:output_type -> tour.UpdateTourExecutionResponse
	10, // 58: tour.TourService.CheckKeypointProximity:output_type -> tour.CheckKeypointProximityResponse
	37, // 59: tour.TourService.GetCompletionStatus:output_type -> tour.GetCompletionStatusResponse
	44, // [44:60] is the sub-list for method output_type
	28, // [28:44] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_tour_tour_proto_init() }
func file_tour_tour_proto_init() {
	if File_tour_tour_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tour_tour_proto_rawDesc), len(file_tour_tour_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   45,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tour_tour_proto_goTypes,
		DependencyIndexes: file_tour_tour_proto_depIdxs,
		MessageInfos:      file_tour_tour_proto_msgTypes,
	}.Build()
	File_tour_tour_proto = out.File
	file_tour_tour_proto_goTypes = nil
	file_tour_tour_proto_depIdxs = nil
}
