// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: purchase/purchase.proto

package purchase

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddToCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TourId        string                 `protobuf:"bytes,2,opt,name=tour_id,json=tourId,proto3" json:"tour_id,omitempty"`
	TourName      string                 `protobuf:"bytes,3,opt,name=tour_name,json=tourName,proto3" json:"tour_name,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddToCartRequest) Reset() {
	*x = AddToCartRequest{}
	mi := &file_purchase_purchase_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddToCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToCartRequest) ProtoMessage() {}

func (x *AddToCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_purchase_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToCartRequest.ProtoReflect.Descriptor instead.
func (*AddToCartRequest) Descriptor() ([]byte, []int) {
	return file_purchase_purchase_proto_rawDescGZIP(), []int{0}
}

func (x *AddToCartRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddToCartRequest) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

func (x *AddToCartRequest) GetTourName() string {
	if x != nil {
		return x.TourName
	}
	return ""
}

func (x *AddToCartRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type AddToCartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Total         float64                `protobuf:"fixed64,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddToCartResponse) Reset() {
	*x = AddToCartResponse{}
	mi := &file_purchase_purchase_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddToCartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToCartResponse) ProtoMessage() {}

func (x *AddToCartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_purchase_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToCartResponse.ProtoReflect.Descriptor instead.
func (*AddToCartResponse) Descriptor() ([]byte, []int) {
	return file_purchase_purchase_proto_rawDescGZIP(), []int{1}
}

func (x *AddToCartResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *AddToCartResponse) GetTotal() float64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type RemoveFromCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TourId        string                 `protobuf:"bytes,2,opt,name=tour_id,json=tourId,proto3" json:"tour_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFromCartRequest) Reset() {
	*x = RemoveFromCartRequest{}
	mi := &file_purchase_purchase_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFromCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFromCartRequest) ProtoMessage() {}

func (x *RemoveFromCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_purchase_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFromCartRequest.ProtoReflect.Descriptor instead.
func (*RemoveFromCartRequest) Descriptor() ([]byte, []int) {
	return file_purchase_purchase_proto_rawDescGZIP(), []int{2}
}

func (x *RemoveFromCartRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RemoveFromCartRequest) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

type RemoveFromCartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Total         float64                `protobuf:"fixed64,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFromCartResponse) Reset() {
	*x = RemoveFromCartResponse{}
	mi := &file_purchase_purchase_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFromCartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFromCartResponse) ProtoMessage() {}

func (x *RemoveFromCartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_purchase_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFromCartResponse.ProtoReflect.Descriptor instead.
func (*RemoveFromCartResponse) Descriptor() ([]byte, []int) {
	return file_purchase_purchase_proto_rawDescGZIP(), []int{3}
}

func (x *RemoveFromCartResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *RemoveFromCartResponse) GetTotal() float64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCartRequest) Reset() {
	*x = GetCartRequest{}
	mi := &file_purchase_purchase_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCartRequest) ProtoMessage() {}

func (x *GetCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_purchase_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCartRequest.ProtoReflect.Descriptor instead.
func (*GetCartRequest) Descriptor() ([]byte, []int) {
	return file_purchase_purchase_proto_rawDescGZIP(), []int{4}
}

func (x *GetCartRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CartItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TourId        string                 `protobuf:"bytes,1,opt,name=tour_id,json=tourId,proto3" json:"tour_id,omitempty"`
	TourName      string                 `protobuf:"bytes,2,opt,name=tour_name,json=tourName,proto3" json:"tour_name,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartItem) Reset() {
	*x = CartItem{}
	mi := &file_purchase_purchase_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartItem) ProtoMessage() {}

func (x *CartItem) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_purchase_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartItem.ProtoReflect.Descriptor instead.
func (*CartItem) Descriptor() ([]byte, []int) {
	return file_purchase_purchase_proto_rawDescGZIP(), []int{5}
}

func (x *CartItem) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

func (x *CartItem) GetTourName() string {
	if x != nil {
		return x.TourName
	}
	return ""
}

func (x *CartItem) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CartItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetCartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*CartItem            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         float64                `protobuf:"fixed64,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCartResponse) Reset() {
	*x = GetCartResponse{}
	mi := &file_purchase_purchase_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCartResponse) ProtoMessage() {}

func (x *GetCartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_purchase_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCartResponse.ProtoReflect.Descriptor instead.
func (*GetCartResponse) Descriptor() ([]byte, []int) {
	return file_purchase_purchase_proto_rawDescGZIP(), []int{6}
}

func (x *GetCartResponse) GetItems() []*CartItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetCartResponse) GetTotal() float64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CheckoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckoutRequest) Reset() {
	*x = CheckoutRequest{}
	mi := &file_purchase_purchase_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckoutRequest) ProtoMessage() {}

func (x *CheckoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_purchase_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckoutRequest.ProtoReflect.Descriptor instead.
func (*CheckoutRequest) Descriptor() ([]byte, []int) {
	return file_purchase_purchase_proto_rawDescGZIP(), []int{7}
}

func (x *CheckoutRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type PurchaseToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TourId        string                 `protobuf:"bytes,1,opt,name=tour_id,json=tourId,proto3" json:"tour_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurchaseToken) Reset() {
	*x = PurchaseToken{}
	mi := &file_purchase_purchase_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurchaseToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseToken) ProtoMessage() {}

func (x *PurchaseToken) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_purchase_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseToken.ProtoReflect.Descriptor instead.
func (*PurchaseToken) Descriptor() ([]byte, []int) {
	return file_purchase_purchase_proto_rawDescGZIP(), []int{8}
}

func (x *PurchaseToken) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

func (x *PurchaseToken) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *PurchaseToken) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type CheckoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Tokens        []*PurchaseToken       `protobuf:"bytes,2,rep,name=tokens,proto3" json:"tokens,omitempty"`
	Total         float64                `protobuf:"fixed64,3,opt,name=total,proto3" json:"total,omitempty"`
	PurchaseId    string                 `protobuf:"bytes,4,opt,name=purchase_id,json=purchaseId,proto3" json:"purchase_id,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckoutResponse) Reset() {
	*x = CheckoutResponse{}
	mi := &file_purchase_purchase_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckoutResponse) ProtoMessage() {}

func (x *CheckoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_purchase_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckoutResponse.ProtoReflect.Descriptor instead.
func (*CheckoutResponse) Descriptor() ([]byte, []int) {
	return file_purchase_purchase_proto_rawDescGZIP(), []int{9}
}

func (x *CheckoutResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CheckoutResponse) GetTokens() []*PurchaseToken {
	if x != nil {
		return x.Tokens
	}
	return nil
}

func (x *CheckoutResponse) GetTotal() float64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *CheckoutResponse) GetPurchaseId() string {
	if x != nil {
		return x.PurchaseId
	}
	return ""
}

func (x *CheckoutResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HasPurchasedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TourId        string                 `protobuf:"bytes,2,opt,name=tour_id,json=tourId,proto3" json:"tour_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HasPurchasedRequest) Reset() {
	*x = HasPurchasedRequest{}
	mi := &file_purchase_purchase_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasPurchasedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasPurchasedRequest) ProtoMessage() {}

func (x *HasPurchasedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_purchase_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasPurchasedRequest.ProtoReflect.Descriptor instead.
func (*HasPurchasedRequest) Descriptor() ([]byte, []int) {
	return file_purchase_purchase_proto_rawDescGZIP(), []int{10}
}

func (x *HasPurchasedRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *HasPurchasedRequest) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

type HasPurchasedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Purchased     bool                   `protobuf:"varint,1,opt,name=purchased,proto3" json:"purchased,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HasPurchasedResponse) Reset() {
	*x = HasPurchasedResponse{}
	mi := &file_purchase_purchase_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasPurchasedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasPurchasedResponse) ProtoMessage() {}

func (x *HasPurchasedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_purchase_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasPurchasedResponse.ProtoReflect.Descriptor instead.
func (*HasPurchasedResponse) Descriptor() ([]byte, []int) {
	return file_purchase_purchase_proto_rawDescGZIP(), []int{11}
}

func (x *HasPurchasedResponse) GetPurchased() bool {
	if x != nil {
		return x.Purchased
	}
	return false
}

func (x *HasPurchasedResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetPurchasesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPurchasesRequest) Reset() {
	*x = GetPurchasesRequest{}
	mi := &file_purchase_purchase_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPurchasesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPurchasesRequest) ProtoMessage() {}

func (x *GetPurchasesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_purchase_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPurchasesRequest.ProtoReflect.Descriptor instead.
func (*GetPurchasesRequest) Descriptor() ([]byte, []int) {
	return file_purchase_purchase_proto_rawDescGZIP(), []int{12}
}

func (x *GetPurchasesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type PurchaseInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PurchaseId    string                 `protobuf:"bytes,1,opt,name=purchase_id,json=purchaseId,proto3" json:"purchase_id,omitempty"`
	TourId        string                 `protobuf:"bytes,2,opt,name=tour_id,json=tourId,proto3" json:"tour_id,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurchaseInfo) Reset() {
	*x = PurchaseInfo{}
	mi := &file_purchase_purchase_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurchaseInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseInfo) ProtoMessage() {}

func (x *PurchaseInfo) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_purchase_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseInfo.ProtoReflect.Descriptor instead.
func (*PurchaseInfo) Descriptor() ([]byte, []int) {
	return file_purchase_purchase_proto_rawDescGZIP(), []int{13}
}

func (x *PurchaseInfo) GetPurchaseId() string {
	if x != nil {
		return x.PurchaseId
	}
	return ""
}

func (x *PurchaseInfo) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

func (x *PurchaseInfo) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *PurchaseInfo) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *PurchaseInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetPurchasesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Purchases     []*PurchaseInfo        `protobuf:"bytes,1,rep,name=purchases,proto3" json:"purchases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPurchasesResponse) Reset() {
	*x = GetPurchasesResponse{}
	mi := &file_purchase_purchase_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPurchasesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPurchasesResponse) ProtoMessage() {}

func (x *GetPurchasesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_purchase_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPurchasesResponse.ProtoReflect.Descriptor instead.
func (*GetPurchasesResponse) Descriptor() ([]byte, []int) {
	return file_purchase_purchase_proto_rawDescGZIP(), []int{14}
}

func (x *GetPurchasesResponse) GetPurchases() []*PurchaseInfo {
	if x != nil {
		return x.Purchases
	}
	return nil
}

var File_purchase_purchase_proto protoreflect.FileDescriptor

const file_purchase_purchase_proto_rawDesc = "" +
	"\n" +
	"\x17purchase/purchase.proto\x12\bpurchase\x1a\x1cgoogle/api/annotations.proto\"w\n" +
	"\x10AddToCartRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\atour_id\x18\x02 \x01(\tR\x06tourId\x12\x1b\n" +
	"\ttour_name\x18\x03 \x01(\tR\btourName\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\"9\n" +
	"\x11AddToCartResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x01R\x05total\"I\n" +
	"\x15RemoveFromCartRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\atour_id\x18\x02 \x01(\tR\x06tourId\">\n" +
	"\x16RemoveFromCartResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x01R\x05total\")\n" +
	"\x0eGetCartRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"u\n" +
	"\bCartItem\x12\x17\n" +
	"\atour_id\x18\x01 \x01(\tR\x06tourId\x12\x1b\n" +
	"\ttour_name\x18\x02 \x01(\tR\btourName\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\"Q\n" +
	"\x0fGetCartResponse\x12(\n" +
	"\x05items\x18\x01 \x03(\v2\x12.purchase.CartItemR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x01R\x05total\"*\n" +
	"\x0fCheckoutRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"T\n" +
	"\rPurchaseToken\x12\x17\n" +
	"\atour_id\x18\x01 \x01(\tR\x06tourId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\"\xae\x01\n" +
	"\x10CheckoutResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12/\n" +
	"\x06tokens\x18\x02 \x03(\v2\x17.purchase.PurchaseTokenR\x06tokens\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x01R\x05total\x12\x1f\n" +
	"\vpurchase_id\x18\x04 \x01(\tR\n" +
	"purchaseId\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\"G\n" +
	"\x13HasPurchasedRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\atour_id\x18\x02 \x01(\tR\x06tourId\"J\n" +
	"\x14HasPurchasedResponse\x12\x1c\n" +
	"\tpurchased\x18\x01 \x01(\bR\tpurchased\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\".\n" +
	"\x13GetPurchasesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x93\x01\n" +
	"\fPurchaseInfo\x12\x1f\n" +
	"\vpurchase_id\x18\x01 \x01(\tR\n" +
	"purchaseId\x12\x17\n" +
	"\atour_id\x18\x02 \x01(\tR\x06tourId\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\"L\n" +
	"\x14GetPurchasesResponse\x124\n" +
	"\tpurchases\x18\x01 \x03(\v2\x16.purchase.PurchaseInfoR\tpurchases2\xdb\x05\n" +
	"\x0fPurchaseService\x12m\n" +
	"\tAddToCart\x12\x1a.purchase.AddToCartRequest\x1a\x1b.purchase.AddToCartResponse\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/api/purchase/{user_id}/cart\x12\x83\x01\n" +
	"\x0eRemoveFromCart\x12\x1f.purchase.RemoveFromCartRequest\x1a .purchase.RemoveFromCartResponse\".\x82\xd3\xe4\x93\x02(*&/api/purchase/{user_id}/cart/{tour_id}\x12d\n" +
	"\aGetCart\x12\x18.purchase.GetCartRequest\x1a\x19.purchase.GetCartResponse\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/api/purchase/{user_id}/cart\x12n\n" +
	"\bCheckout\x12\x19.purchase.CheckoutRequest\x1a\x1a.purchase.CheckoutResponse\"+\x82\xd3\xe4\x93\x02%:\x01*\" /api/purchase/{user_id}/checkout\x12\x82\x01\n" +
	"\fHasPurchased\x12\x1d.purchase.HasPurchasedRequest\x1a\x1e.purchase.HasPurchasedResponse\"3\x82\xd3\xe4\x93\x02-\x12+/api/purchase/{user_id}/purchased/{tour_id}\x12x\n" +
	"\fGetPurchases\x12\x1d.purchase.GetPurchasesRequest\x1a\x1e.purchase.GetPurchasesResponse\")\x82\xd3\xe4\x93\x02#\x12!/api/purchase/{user_id}/purchasesB\x10Z\x0eproto/purchaseb\x06proto3"

var (
	file_purchase_purchase_proto_rawDescOnce sync.Once
	file_purchase_purchase_proto_rawDescData []byte
)

func file_purchase_purchase_proto_rawDescGZIP() []byte {
	file_purchase_purchase_proto_rawDescOnce.Do(func() {
		file_purchase_purchase_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_purchase_purchase_proto_rawDesc), len(file_purchase_purchase_proto_rawDesc)))
	})
	return file_purchase_purchase_proto_rawDescData
}

var file_purchase_purchase_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_purchase_purchase_proto_goTypes = []any{
	(*AddToCartRequest)(nil),       // 0: purchase.AddToCartRequest
	(*AddToCartResponse)(nil),      // 1: purchase.AddToCartResponse
	(*RemoveFromCartRequest)(nil),  // 2: purchase.RemoveFromCartRequest
	(*RemoveFromCartResponse)(nil), // 3: purchase.RemoveFromCartResponse
	(*GetCartRequest)(nil),         // 4: purchase.GetCartRequest
	(*CartItem)(nil),               // 5: purchase.CartItem
	(*GetCartResponse)(nil),        // 6: purchase.GetCartResponse
	(*CheckoutRequest)(nil),        // 7: purchase.CheckoutRequest
	(*PurchaseToken)(nil),          // 8: purchase.PurchaseToken
	(*CheckoutResponse)(nil),       // 9: purchase.CheckoutResponse
	(*HasPurchasedRequest)(nil),    // 10: purchase.HasPurchasedRequest
	(*HasPurchasedResponse)(nil),   // 11: purchase.HasPurchasedResponse
	(*GetPurchasesRequest)(nil),    // 12: purchase.GetPurchasesRequest
	(*PurchaseInfo)(nil),           // 13: purchase.PurchaseInfo
	(*GetPurchasesResponse)(nil),   // 14: purchase.GetPurchasesResponse
}
var file_purchase_purchase_proto_depIdxs = []int32{
	5,  // 0: purchase.GetCartResponse.items:type_name -> purchase.CartItem
	8,  // 1: purchase.CheckoutResponse.tokens:type_name -> purchase.PurchaseToken
	13, // 2: purchase.GetPurchasesResponse.purchases:type_name -> purchase.PurchaseInfo
	0,  // 3: purchase.PurchaseService.AddToCart:input_type -> purchase.AddToCartRequest
	2,  // 4: purchase.PurchaseService.RemoveFromCart:input_type -> purchase.RemoveFromCartRequest
	4,  // 5: purchase.PurchaseService.GetCart:input_type -> purchase.GetCartRequest
	7,  // 6: purchase.PurchaseService.Checkout:input_type -> purchase.CheckoutRequest
	10, // 7: purchase.PurchaseService.HasPurchased:input_type -> purchase.HasPurchasedRequest
	12, // 8: purchase.PurchaseService.GetPurchases:input_type -> purchase.GetPurchasesRequest
	1,  // 9: purchase.PurchaseService.AddToCart:output_type -> purchase.AddToCartResponse
	3,  // 10: purchase.PurchaseService.RemoveFromCart:output_type -> purchase.RemoveFromCartResponse
	6,  // 11: purchase.PurchaseService.GetCart:output_type -> purchase.GetCartResponse
	9,  // 12: purchase.PurchaseService.Checkout:output_type -> purchase.CheckoutResponse
	11, // 13: purchase.PurchaseService.HasPurchased:output_type -> purchase.HasPurchasedResponse
	14, // 14: purchase.PurchaseService.GetPurchases:output_type -> purchase.GetPurchasesResponse
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_purchase_purchase_proto_init() }
func file_purchase_purchase_proto_init() {
	if File_purchase_purchase_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_purchase_purchase_proto_rawDesc), len(file_purchase_purchase_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_purchase_purchase_proto_goTypes,
		DependencyIndexes: file_purchase_purchase_proto_depIdxs,
		MessageInfos:      file_purchase_purchase_proto_msgTypes,
	}.Build()
	File_purchase_purchase_proto = out.File
	file_purchase_purchase_proto_goTypes = nil
	file_purchase_purchase_proto_depIdxs = nil
}
